<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'geoip\maxmind'               => __DIR__ . '/src/BuyGenericRTB/geoip/maxmind.php',
  'rtbbuyv22\RtbBuyV22Bid'      => __DIR__ . '/src/BuyGenericRTB/rtbbuyv22/RtbBuyV22Bid.php',
  'rtbbuyv22\RtbBuyV22Init'     => __DIR__ . '/src/BuyGenericRTB/rtbbuyv22/RtbBuyV22Init.php',
  'rtbbuyv22\RtbBuyV22Logger'   => __DIR__ . '/src/BuyGenericRTB/rtbbuyv22/RtbBuyV22Logger.php',
  'rtbbuyv22\RtbBuyV22Workflow' => __DIR__ . '/src/BuyGenericRTB/rtbbuyv22/RtbBuyV22Workflow.php',
  'rtbbuyv\RtbBuyBid'      => __DIR__ . '/src/BuyGenericRTB/rtbbuy/RtbBuyBid.php',
  'rtbbuyv\RtbBuyInit'     => __DIR__ . '/src/BuyGenericRTB/rtbbuy/RtbBuyInit.php',
  'rtbbuyv\RtbBuyLogger'   => __DIR__ . '/src/BuyGenericRTB/rtbbuy/RtbBuyLogger.php',
  'rtbbuyv\RtbBuyWorkflow' => __DIR__ . '/src/BuyGenericRTB/rtbbuy/RtbBuyWorkflow.php',
  'mainappc'                    => __DIR__ . '/src/BuyGenericRTB/_geoip/benchmark.php',
  'mobileutil\MobileDetect'     => __DIR__ . '/src/BuyGenericRTB/_mobile/MobileDetect.php',
  'mobileutil\MobileDeviceType' => __DIR__ . '/src/BuyGenericRTB/_mobile/MobileDeviceType.php',
);
