<?php echo $menu_tpl; ?>

<div>
    Select interval
    <select id="interval_type">
        <option value="0" selected>12 Hours</option>
        <option value="1">set the interval</option>
    </select>

    <div id="datetimepicker1" class="input-append date datetimepicker">
        <input id="time_from" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="from" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <div id="datetimepicker2" class="input-append date datetimepicker">
        <input id="time_to" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="to" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <input id="interval_setter_btn" class="btn report_btn"  data-refresh="0" data-excel="0" data-action="getContractImpressionsPerTime" value="Show" type="button" />
    <input id="refresh_cache_btn" class="btn report_btn" data-refresh="1"  data-excel="0" data-action="getContractImpressionsPerTime"  data-tab="4" value="Refresh" type="button" />
    <input id="download_excel_btn" class="btn report_btn" data-refresh="0"  data-excel="1" data-action="getContractImpressionsPerTime"  data-tab="5" value="Download Excel" type="button" />
</div>

<div id="report_list">
    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>
    </div>

    <table>
        <thead>
            <tr>
                <?php foreach ($impressions_header as $key=>$one): ?>
                    <th><?php echo (!empty($one)) ? $one : $key; ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($impressions as $one): ?>
                <tr>
                    <?php foreach ($one as $two): ?>
                        <td><?php echo $two; ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        	<tr>
            <?php foreach ($totals as $name => $value): ?>
            	<td><?php echo $value; ?></td>
            <?php endforeach; ?>
            </tr>
        </tbody>
    </table>

    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>

    </div>
</div>
