<?php echo $menu_tpl; ?>

<div>
    Select interval
    <select id="interval_type">
        <option value="0" selected>12 Hours</option>
        <option value="1">set the interval</option>
    </select>

    <div id="datetimepicker1" class="input-append date datetimepicker">
        <input id="time_from" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="from" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <div id="datetimepicker2" class="input-append date datetimepicker">
        <input id="time_to" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="to" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <input id="interval_setter_btn" class="btn report_btn"  data-refresh="0" data-action="getContractImpressionsPerTime" value="Show" type="button" />
    <input id="refresh_chache_btn" class="btn report_btn" data-refresh="1"  data-action="getContractImpressionsPerTime"  data-tab="4" value="Refresh" type="button" />
</div>

<div id="report_list">
    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>
    </div>

    <table>
        <thead>
            <tr>
                <th>MDYH</th>
                <th>Impressions</th>
                <th>Spend</th>
                <th>DateCreated</th>
                <th>DateUpdated</th>
                <th>PublisherAdZone</th>
            </tr>
        </thead>
        <tbody>
<?php foreach ($impressions as $one): 
			if (is_object($one)):
?>
                <tr>
                    <td><?php echo $one->MDYH; ?></td>
                    <td><?php echo $one->Impressions; ?></td>
                    <td><?php echo $one->SpendTotalNet; ?></td>
                    <td><?php echo $one->DateCreated; ?></td>
                    <td><?php echo $one->DateUpdated; ?></td>
                    <td><?php echo $one->AdName; ?></td>
                </tr>
<?php	endif;
	 endforeach; ?>
        </tbody>
    </table>

    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>

    </div>
</div>

<div id="spend_per_webdomain">
    <table>
        <thead>
            <tr>
                <th>Impressions Total</th>
                <th>Spend Total</th>
                <th>Ad name</th>
                <th>WebDomain</th>
                <th>Banner name</th>
                <th>User</th>
            </tr>
        </thead>
        <tbody>
<?php foreach ($spend_per_webdomain as $one): ?>
                <tr>
                    <td><?php echo $one->ImpressionsTotal; ?></td>
                    <td><?php echo $one->SpendTotalNet; ?></td>
                    <td><?php echo $one->AdName; ?></td>
                    <td><?php echo $one->WebDomain; ?></td>
                    <td><?php echo $one->banner_name; ?></td>
                    <td><?php echo $one->user_login; ?></td>
                </tr>
<?php endforeach; ?>
        </tbody>
    </table>

</div>