<?php echo $menu_tpl; ?>
<div>
    Select interval
    <select id="interval_type">
        <option value="0" selected>15 minutes</option>
        <option value="1">set the interval</option>
    </select>

    <div id="datetimepicker1" class="input-append date datetimepicker">
        <input id="time_from" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="from" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <div id="datetimepicker2" class="input-append date datetimepicker">
        <input id="time_to" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="to" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <input id="interval_setter_btn" class="btn report_btn"  data-refresh="0" data-action="getIncomingBidsPerTime" value="Show" type="button" />
    <input id="refresh_chache_btn" class="btn report_btn" data-refresh="1"  data-action="getIncomingBidsPerTime"  data-tab="2" value="Refresh" type="button" />
</div>

<div id="report_list">
    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 15 minutes</a>
    </div>

    <table>
        <thead>
            <tr>
                <?php foreach ($incoming_bids_header as $one): ?>
                    <th><?php echo $one; ?></th>
                <?php endforeach; ?>
<!--                <th>Buy Side Partner </th>
                <th>MDYH</th>
                <th>BidsCounter</th>
                <th>DateCreated</th>
                <th>DateUpdated</th>
                <th>AdCampaign</th>-->
            </tr>
        </thead>
        <tbody>
<?php foreach ($incoming_bids as $one): ?>
                <tr>
                    <?php foreach ($one as $two): ?>
                        <td><?php echo $two;?></td>
                    <?php endforeach;?>
<!--                    <td><?php // echo $one->BuySidePartnerID; ?></td>
                    <td><?php // echo $one->MDYH; ?></td>
                    <td><?php // echo $one->BidsCounter; ?></td>
                    <td><?php // echo $one->DateCreated; ?></td>
                    <td><?php // echo $one->DateUpdated; ?></td>
                    <td><?php // echo $one->Name; ?></td>-->
                </tr>
<?php endforeach; ?>
        </tbody>
    </table>

    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 15 minutes</a>

    </div>
</div>

<div id="average_bids_area">
    <table>
        <thead>
            <tr>
                <?php foreach ($average_bids_header as $one): ?>
                    <th><?php echo $one; ?></th>
                <?php endforeach; ?>
<!--                <th>Buy Side Partner</th>
                <th>Average Bids</th>
                <th>Total Bids</th>
                <th>Ad Campaign Banner</th>
                <th>AdCampaign</th>
                <th>User</th>-->
            </tr>
        </thead>
        <tbody>
<?php foreach ($average_bids as $one): ?>
                <tr>
                    <?php foreach ($one as $two): ?>
                        <td><?php echo $two;?></td>
                    <?php endforeach;?>
<!--                    <td><?php //echo $one->BuySidePartnerID; ?></td>
                    <td><?php //echo $one->avg_bids; ?></td>
                    <td><?php //echo $one->total_bids; ?></td>
                    <td><?php //echo $one->banner_name; ?></td>
                    <td><?php //echo $one->Name; ?></td>
                    <td><?php //echo $one->user_login; ?></td>-->
                </tr>
<?php endforeach; ?>
        </tbody>
    </table>

</div>