<?php echo $menu_tpl; ?>
<div>
    Select interval
    <select id="interval_type">
        <option value="0" selected>12 Hours</option>
        <option value="1">set the interval</option>
    </select>

    <div id="datetimepicker1" class="input-append date datetimepicker">
        <input id="time_from" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="from" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <div id="datetimepicker2" class="input-append date datetimepicker">
        <input id="time_to" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="to" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <input id="interval_setter_btn" class="btn report_btn"  data-refresh="0" data-action="getOutgoingBidsPerTime" value="Show" type="button" />
    <input id="refresh_chache_btn" class="btn report_btn" data-refresh="1" data-action="getOutgoingBidsPerTime"  data-tab="3" value="Refresh" type="button" />
</div>

<div id="report_list">
    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>
    </div>

    <table>
        <thead>
            <tr>
                <?php foreach ($outgoing_bids_header as $one): ?>
                    <th><?php echo $one; ?></th>
                <?php endforeach; ?>
<!--                <th>SellSidePartnerID</th>
                <th>MDYH</th>
                <th>BidsWonCounter</th>
                <th>BidsLostCounter</th>
                <th>BidsErrorCounter</th>
                <th>SpendTotal</th>
                <th>DateCreated</th>
                <th>DateUpdated</th>
                <th>PublisherAdZone</th>-->
            </tr>
        </thead>
        <tbody>
<?php foreach ($outgoing_bids as $one): ?>
                
                    <?php 
                    if (is_array($one)):
                    foreach ($one as $two): ?>
                    <tr>
	                    <td><?php echo $two->SellSidePartnerID; ?></td>
	                    <td><?php echo $two->MDYH; ?></td>
	                    <td><?php echo $two->BidsWonCounter; ?></td>
	                    <td><?php echo $two->BidsLostCounter; ?></td>
	                    <td><?php echo $two->BidsErrorCounter; ?></td>
	                    <td><?php echo $two->SpendTotalNet; ?></td>
	                    <td><?php echo $two->DateCreated; ?></td>
	                    <td><?php echo $two->DateUpdated; ?></td>
	                    <td><?php echo $two->AdName; ?></td>
                    </tr>
                    <?php endforeach;
                    endif; ?>
                
<?php endforeach; ?>
        	<tr>
            <?php foreach ($totals as $name => $value): ?>
            	<td><?php echo $value; ?></td>
            <?php endforeach; ?>
            </tr>
        </tbody>
    </table>

    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>
    </div>
</div>
