<?php echo $menu_tpl; ?>
<div>
    Select interval
    <select id="interval_type">
        <option value="0" selected>12 Hours</option>
        <option value="1">set the interval</option>
    </select>

    <div id="datetimepicker1" class="input-append date datetimepicker">
        <input id="time_from" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="from" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <div id="datetimepicker2" class="input-append date datetimepicker">
        <input id="time_to" data-format="yyyy-MM-dd hh:mm" type="text" placeholder="to" disabled />
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
        </span>
    </div>

    <input id="interval_setter_btn" class="btn report_btn"  data-refresh="0"  data-excel="0" data-action="getImpressionsCurrentSpendPerTime" value="Show" type="button" />
    <input id="refresh_cache_btn" class="btn report_btn" data-refresh="1" data-excel="0" data-action="getImpressionsCurrentSpendPerTime" data-tab="5" value="Refresh" type="button" />
    <input id="download_excel_btn" class="btn report_btn" data-refresh="0" data-excel="1" data-action="getImpressionsCurrentSpendPerTime" data-tab="6" value="Download Excel" type="button" />
</div>

<div id="report_list">
    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>
    </div>

    <table>
        <thead>
            <tr>
                <?php foreach ($impressions_spend_header as $key=>$one): ?>
                    <th><?php echo (!empty($one)) ? $one : $key; ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody> 	 	 	 	 	 	 	
            <?php foreach ($impressions_spend as $one): ?>
               		<?php if (is_array($one)): ?>	
                    <?php foreach ($one as $two): ?>
                    <tr>
                        <?php echo isset($two->BuySidePartnerID) ? '<td>' . $two->BuySidePartnerID . '</td>' : ""; ?>
                        <td><?php echo $two->MDYH; ?></td>
                        <td><?php echo $two->ImpressionsCounter; ?></td>
                        <td><?php echo $two->CurrentSpendGross; ?></td>
                        <?php echo isset($two->CurrentSpendNet) ? '<td>' . $two->CurrentSpendNet . '</td>' : ""; ?>
                        <?php echo isset($two->AverageBidCurrentSpendNet) ? '<td>' . $two->AverageBidCurrentSpendNet . '</td>' : ""; ?>
                        <td><?php echo $two->AverageBidCurrentSpendGross; ?></td>
                        <td><?php echo $two->DateCreated; ?></td>
                        <td><?php echo $two->DateUpdated; ?></td>
                        <td><?php echo $two->Name; ?></td>
                    </tr>
                    <?php endforeach; ?>
                    <?php endif; ?>	
                
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="step_navigation">
        <a href="#" data-step="2" class="step_btn">Prev 12 Hours</a>
    </div>
</div>

<div id="total_spend_area">
    <h3>Total spend</h3>
    <table>
        <thead>
            <tr>
                <?php foreach ($user_spend_statistic_header as $key => $one): ?>
                    <th><?php echo (!empty($one)) ? $one : $key; ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($user_spend_statistic as $one): ?>
                <tr>
                    <?php foreach ($one as $two): ?>
                        <td><?php echo $two; ?></td>
                    <?php endforeach; ?>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>


</div>