<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'pinger\PingManager'          => __DIR__ . '/src/SellGenericRTB/pinger/PingManager.php',
  'pinger\RTBPinger'            => __DIR__ . '/src/SellGenericRTB/pinger/RTBPinger.php',
  'rtbsellv22\RtbSellV22Bid'    => __DIR__ . '/src/SellGenericRTB/rtbsellv22/RtbSellV22Bid.php',
  'rtbsellv22\RtbSellV22Init'   => __DIR__ . '/src/SellGenericRTB/rtbsellv22/RtbSellV22Init.php',
  'rtbsellv22\RtbSellV22Logger' => __DIR__ . '/src/SellGenericRTB/rtbsellv22/RtbSellV22Logger.php',
);
