<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BuyLoopbackPartner\Module'                              => __DIR__ . '/BuyLoopbackPartner/Module.php',
  'BuyLoopbackPartner\Controller\IndexController'          => __DIR__ . '/BuyLoopbackPartner/src/BuyLoopbackPartner/Controller/IndexController.php',
  'buyloopbackpartner\LoopbackPartnerBid'                  => __DIR__ . '/BuyLoopbackPartner/src/BuyLoopbackPartner/loopbackpartner/LoopbackPartnerBid.php',
  'buyloopbackpartner\LoopbackPartnerInit'                 => __DIR__ . '/BuyLoopbackPartner/src/BuyLoopbackPartner/loopbackpartner/LoopbackPartnerInit.php',
  'buyloopbackpartner\LoopbackPartnerLogger'               => __DIR__ . '/BuyLoopbackPartner/src/BuyLoopbackPartner/loopbackpartner/LoopbackPartnerLogger.php',
  'buyloopbackpartner\LoopbackPartnerWorkflow'             => __DIR__ . '/BuyLoopbackPartner/src/BuyLoopbackPartner/loopbackpartner/LoopbackPartnerWorkflow.php',
  'GenericBuysidePartner\Module'                           => __DIR__ . '/GenericBuysidePartner/Module.php',
  'GenericBuysidePartner\Controller\IndexController'       => __DIR__ . '/GenericBuysidePartner/src/GenericBuysidePartner/Controller/IndexController.php',
  'buygenericbuysidepartner\GenericBuysidePartnerBid'      => __DIR__ . '/GenericBuysidePartner/src/GenericBuysidePartner/genericbuysidepartner/GenericBuysidePartnerBid.php',
  'buygenericbuysidepartner\GenericBuysidePartnerInit'     => __DIR__ . '/GenericBuysidePartner/src/GenericBuysidePartner/genericbuysidepartner/GenericBuysidePartnerInit.php',
  'buygenericbuysidepartner\GenericBuysidePartnerLogger'   => __DIR__ . '/GenericBuysidePartner/src/GenericBuysidePartner/genericbuysidepartner/GenericBuysidePartnerLogger.php',
  'buygenericbuysidepartner\GenericBuysidePartnerWorkflow' => __DIR__ . '/GenericBuysidePartner/src/GenericBuysidePartner/genericbuysidepartner/GenericBuysidePartnerWorkflow.php',
);
