<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart(); ?>
/*$(function(){
    $('#dpsd').datepicker().datepicker().on('show', popup);
    $('#dped').datepicker().datepicker().on('show', popup);
});*/
$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  ?>
<ul class="breadcrumb breadcrumb-heading">
    <li><a href="/publisher/">Domains</a><span class="divider">/</span></li>
    <li>Create New Domain</li>
    </ul>    
<?php 
    if($error_message != "" && $error_message !== null && isset($error_message)):
    	echo '<div id="cdn_form_success" class="alert alert-error" style="margin: 5px;">'. $error_message .'</div>';
    endif;
?>
<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
<form id="domain" class="form-horizontal form-top-magin" name="domain" method="post" action="/publisher/createdomain">
<input type="hidden" value="" name="PublisherWebsiteID">
<div class="control-group">
    <label for="webdomain" class="control-label">Web Domain</label>
    <div class="controls">
    <input type="text" value="" maxlength="255" class="zone-txtarea" id="WebDomain" name="WebDomain">    </div>
    </div>
    
<div class="control-group">
    <label for="IABCategory" class="control-label">IABCategory</label>
    <div class="controls">
    <select class="zone-txtarea" id="IABCategory" name="IABCategory">
	<?php 
     foreach($vertical_map as $key=>$value): 
	 	echo '<option value="'. $key .'">'. $value .'</option>';
	 endforeach;
	 ?>
</select>
    </div>
    </div>  
    
<div class="control-group">
    <label for="desc" class="control-label">Description</label>
    <div class="controls">
    <textarea maxlength="5000" class="zone-txtarea" id="Description" name="Description"></textarea>    </div>
    </div> 
    <?php  if ($is_super_admin || $is_domain_admin):   ?>
    <div class="control-group">
    <label for="desc" class="control-label">Platform Connection
    </label><div class="controls">
    <input type="checkbox" value="1" id="EnablePlatformConnection" name="EnablePlatformConnection" /> 
    <span style="position: absolute; margin-left: 15px; margin-top: 2px; cursor: pointer;" title="Publisher Websites enabled on Platform Connection will be available to all Exchange Media Buyers for impression auction bidding"><img style="border: 0; margin-bottom: 10px;" src="/images/tooltip.jpg" /></span>
     </div>
     </div> 
     <?php  endif;   ?>
<div class="control-group">
    <div class="controls">
    <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Create New Domain</button>
    </div>
    </div>
<input type="hidden" value="<?php echo $domain_owner_id;?>" name="DomainOwnerID">
</form>