<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');

$this->headScript()->captureStart() ?>
<?php $this->headScript()->captureEnd();  ?>
<ul class="breadcrumb breadcrumb-heading">
 <li><a href="/publisher/">Domains</a> <span class="divider">/</span></li>
    <li><a href="/publisher/zone/<?php echo $editResultObj->PublisherWebsiteID;?>"><?php echo $editResultObj->WebDomain;?></a><span class="divider">/</span></li>
    <li class="active">Edit Domain</li>
    </ul>   
<?php 
    if($error_message != "" && $error_message !== null && isset($error_message)):
    	echo '<div id="cdn_form_success" class="alert alert-error" style="margin: 5px;">'. $error_message .'</div>';
    endif;

?>
<?php  /*if($is_admin) { ?>
    <div>
        <?php 
        // If Admin, show which account you are creating for.
            if($impersonate_id == "0" || $impersonate_id == null)
                echo "User: " . $true_user_name;
            else
                echo "User: " . $user_id_list[$impersonate_id];
        ?>
    </div>
    <?php }*/ ?>
 <div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
 
 
 <form id="domain" class="form-horizontal form-top-magin" name="domain" method="post" action="/publisher/editdomain/<?php echo $editResultObj->PublisherWebsiteID;?>/" novalidate="novalidate">
 <div class="control-group">
    <label for="webdomain" class="control-label">Web Domain</label>
    <div class="controls">
    <input type="text" value="<?php echo $editResultObj->WebDomain;?>" maxlength="255" class="zone-txtarea" id="WebDomain" name="WebDomain">    </div>
    </div>
<div class="control-group">
    <label for="IABCategory" class="control-label">IABCategory</label>
    <div class="controls">
    <select class="zone-txtarea" id="IABCategory" name="IABCategory">
	<?php 
     foreach($vertical_map as $key=>$value):
     	$selected = '';
     	if($editResultObj->IABCategory == $key):
     		$selected = 'selected';
     	endif; 
	 	echo '<option value="'. $key .'" '.$selected.'>'. $value .'</option>';
	 endforeach;
	 ?>
</select>
    </div>
    </div>  
<div class="control-group">
    <label for="desc" class="control-label">Description</label>
    <div class="controls">
    <textarea maxlength="5000" class="zone-txtarea" id="Description" name="Description"><?php echo $editResultObj->Description;?></textarea>    </div>
    </div>     
    <div class="controls">
    <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Update Domain</button>
    </div>
    </div>
<input type="hidden" value="<?php echo $editResultObj->DomainOwnerID;?>" name="DomainOwnerID"><div class="control-group">
 <input type="hidden" value="<?php echo $editResultObj->PublisherWebsiteID;?>" name="PublisherWebsiteID">
</form>