<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
	$('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="steps-container step1">
    <div class="span3" style="float: right">  <?php if ($is_domain_admin === true): ?>
    			 
    			 <form name="loginas" id="loginas" action="/private-exchange/publishers/loginasdomain" class="forms pull-left" style="margin-top: 10px;">
    			<span style="font-size: 12px; font-weight: bold;">LOG IN AS USER</span>	
    			 	<select name="userid" onchange="submitForm();">
    			 		<option value="0">PX Admin (<?php echo $true_user_name; ?>)</option>
    					<?php foreach ($user_id_list as $user_info_id => $user_info_name): ?>
    						<option <?php 
							if ($user_info_id == $effective_id): 
								$effective_user_in_dashboard = true; 
								echo 'selected="selected"'; 
							endif; ?> value="<?php echo $user_info_id;?>"><?php echo $user_info_name;?></option>
    					<?php endforeach; ?>
    			 	</select>
    			 </form>
    	<?php endif; ?>    		
    	</div>
<div id="main-container">
    <div class="formbox">      
    	<br clear="all"/>
    <div id="selection-results" class="steps-box">
        <table class="table table-striped table-bordered table-margin">
            <tr>
            <?php 
            foreach($domain_list['header'] as $order => $title):
            	if ($title == "Domain Markup" || $title == "Imps Loss Rate"):
            		echo "\n<th style=\"text-align:center; width: 110px\">" . $title . "</th>\n";
            	else:
            		echo "\n<th style=\"text-align:center;\">" . $title . "</th>\n";
            	endif;
            endforeach;
            ?>
            </tr>
            <?php
            if(count($domain_list["data"]) > 0):
                foreach ($domain_list["data"] AS $row_number => $row_data):
                	$is_rejected = false;
            ?>
                <tr>
                    <td><?php echo $row_number+1; ?></td>
                    <?php foreach ($row_data AS $column_key => $data):
                    	
                    if ($domain_list["meta"][$column_key] == 'AutoApprove'):
                    	continue;
                    endif;
                    $auto_approved = $domain_list_raw[$row_number]["AutoApprove"];
                    $domain_id = $domain_list_raw[$row_number]["PublisherWebsiteID"];
                        ?>
                        <td>
                            <?php 
                                // Change display format according to column specified.
                                switch($domain_list["meta"][$column_key]):
                                    case "WebDomain":
                                        echo $data . " (" . $domain_id .")";
                                        break; 
                                    case "DomainOwnerID":
                                	    echo $domain_owner . " (" . $data . ")";
                                        break;
                                	case "ApprovalFlag":
                                		
                                		$approve_verb = 'Approve';
                                		$reject_verb = 'Reject';
                                		$approved_verb = 'Approved';
                                		$pending_verb = 'Pending';
                                		$rejected_verb = 'Rejected';
                                		
                                		if ($auto_approved == 1):
                                			$approved_verb = 'Auto-Approved';
                                		endif;
                                		
                                	    $admin_approval = array(
                                	           0 => "<strong>" . $pending_verb . "</strong><br /><a href=\"/publisher/approvedomain/" . $domain_id . "\">" . $approve_verb . "</a>"
												. "<br /><a href=\"/publisher/rejectdomain/" . $domain_id . "\">" . $reject_verb . "</a>",
                                               1 => "<a href=\"/publisher/rejectdomain/" . $domain_id . "\">" . $approved_verb . "</a>",
											   2 => "<a href=\"/publisher/approvedomain/" . $domain_id . "\">" . $rejected_verb . "</a>"
    			 	                           );
                                	    $approval = array(0=>$pending_verb,1=>$approved_verb,2=>$rejected_verb);
                                	    
                                	    if (intval($data) == 2):
                                	    	$is_rejected = true;
                                	    endif;
                                	    
                                	    if($is_domain_admin):
                                	        echo $admin_approval[intval($data)];
                                	    else:
                                	        echo $approval[intval($data)];
                                	    endif;
                                        break;
                                    default:
                                        echo $data;
                                        break;
                                endswitch;
                            ?>
                        </td>
                    <?php endforeach; ?>
                    <td>
                    <?php if ($is_domain_admin === true || $is_rejected !== true): ?>
                    	<a href="/publisher/editdomain/<?php echo $domain_id;?>">Edit Domain</a>
                        &nbsp;&nbsp;&nbsp;
                        <!--<a href="/publisher/deletedomain/<?php echo $domain_id; ?>">Delete Domain</a>-->
                        <a href="javascript:void(0);" onclick="deleteDomainModal(<?php echo $domain_id;?>,'<?php echo $domain_list_raw[$row_number]["WebDomain"];?>');">Delete Domain</a>
                        <hr width="100%" />
                        <a href="/publisher/zone/<?php echo $domain_id;?>">Edit/View Zones</a>
                        &nbsp;&nbsp;&nbsp;
                        <a href="/publisher/zone/<?php echo $domain_id;?>/create/">Create Zones</a>
                    <?php else: ?>
                        &nbsp;
                    <?php endif; ?>
                    </td>
                </tr>
            <?php 
                endforeach;
       
            else:
             ?>
                <tr>
                    <td colspan="<?php echo count($domain_list['header']); ?>" style="text-align:center;">There are no results</td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
    </div>
</div>

<!-- Domain Delete Modal -->
<input  type="hidden" name="modal_domain_id" id="modal_domain_id" value="0" />
<div class="modal fade" id="DeleteDomainModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Domain</h4>
      </div>
      <div class="modal-body">
      <div id="domain_alert_msg" class="alert alert-error" style="display: none;">Error</div>
		<p id="msg"></p>
<h5 style="color: #b94a48;">This action is IMMEDIATE and NOT REVERSABLE!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="domain_yes_btn" class="btn btn-primary" onclick="deleteDomainConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="domain_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Domain Delete Modal -->