<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Delivery\Module'                     => __DIR__ . '/Module.php',
  'Delivery\Controller\IndexController' => __DIR__ . '/src/Delivery/Controller/IndexController.php',
);
