<?php
$this->headScript()->appendFile($this->basePath() . '/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/datatables/sitechooser.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/datatables/jquery.dataTables.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/datatables/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/datatables/sitechooser.js');

$current_time = time();
$yesterday_time = $current_time - 86400;
$yesterday = date('m/d/Y', $yesterday_time);

$enddate = date('m/d/Y', time() + (86400 * 30));
$minEndDate = explode("/", $enddate);

$this->headScript()->captureStart();?>

var insertion_order_id = null;

$(function() {
	$( "#startdate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
	    onSelect: function(date){
	        var selectedDate = new Date(date);
	        var msecsInADay = 86400000;
	        var endDate = new Date(selectedDate.getTime() + msecsInADay);
	        $("#enddate").datepicker( "option", "minDate", endDate );
	    }
	});
    
    $( "#enddate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
        minDate:new Date(<?php echo $minEndDate[2];?>,<?php echo $minEndDate[0];?>,<?php echo $minEndDate[1];?>)
	});
	
	$( "#stats-date-ssp" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: true,
        yearRange: "-1:+6",
	});
	
	$( "#stats-date-pc" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: true,
        yearRange: "-1:+6",
	});
	
	$( '#stats-date-ssp-icon' ).click(function() {
          $('#stats-date-ssp').datepicker('show');
    });
	
	$( '#stats-date-pc-icon' ).click(function() {
          $('#stats-date-pc').datepicker('show');
    });
	
	$( '#startdateicon' ).click(function() {
          $('#startdate').datepicker('show');
    });
	
	$( '#enddateicon' ).click(function() {
          $('#enddate').datepicker('show');
    });
});
<?php $this->headScript()->captureEnd();?>
<style type="text/css">
	/*form label.error, form input.submit {
margin-left: 253px;
} */
</style>
    <ul class="breadcrumb">
    <li><a href="/private-exchange/">Insertion Order</a><span class="divider">/</span></li>
    <li>Create Insertion Order</li>
    </ul>
<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display: none;"></div>
<form onsubmit="highlightSelects();" id="campaignform" class="form-horizontal form-top-magin" name="campaignform" method="POST" action="/private-exchange/newinsertionorder">
<fieldset>
<div class="span7">
	    <div class="control-group">
		<label for="campaignname">Order Name</label>
		<input type="text" class="input-medium" name="campaignname">
	</div>
  <div class="control-group">
	    <label for="startdate">Start Date</label>
	   <div class="input-append date">
		  <input name="startdate" id="startdate" class="span2" size="16" type="text" value="<?php echo date('m/d/Y');?>" readonly="readonly" />
		  <span class="add-on" id="startdateicon"><i class="icon-calendar"></i></span>
	   </div>
	</div>
  <div class="control-group">
	    <label for="enddate">End Date</label>
	   <div class="input-append date">
		  <input name="enddate" id="enddate" class="span2" size="16" type="text" value="<?php echo $enddate;?>" readonly="readonly" />
		  <span class="add-on" id="enddateicon"><i class="icon-calendar"></i></span>
	   </div>
	</div>
  <div class="control-group">
		<label for="customername">Customer Name <nobr><span class="hlp"><small><i>(Use this field for your own customer reference if any)</i></small></span></nobr></label>
		<input type="text" class="input-medium" name="customername">
	</div>
	  <div class="control-group">
		<label for="customerid">Customer ID <nobr><span class="hlp"><small><i>(Use this field for your own customer reference if any)</i></small></span></nobr></label>
		<input type="text" name="customerid" class="input-small">
	</div>
  <div class="control-group">
		<label for="maximpressions">Maximum Impressions: <nobr><span class="hlp"><small><i>(Maximum campaign impressions before the bids stop)</i></small></span></nobr></label>
		<input type="text" name="maximpressions" value="1000000"  class="input-small">
	</div>
  <div class="control-group">
		<label for="maxspend">Maximum Spend: <nobr><span class="hlp"><small><i>(Maximum campaign $$$ spent before the bids stop)</i></small></span></nobr></label>
	    <div class="input-prepend">
		<span class="add-on">$</span>
	    <input type="text" value="100.00" class="input-mini" maxlength="20" id="maxspend" name="maxspend">    </div>
    </div>
  </div>
  <div class="span7">
  <div class="inventory-container">
  	<h4 class="no-pad">Private Exchange Inventory Feeds
  	<br /><small>[ Default Value for new Line Items ]</small></h4>
  	<div>
  	<input type="button" class="btn btn-primary btn-margin" name="AddPcFeed" value="Add" onclick="showChooserPx();" />
  	<input type="button" class="btn btn-primary btn-margin next" name="RemovePxFeed" value="Remove" onclick="removeSelectedPxItems();" />
  	</div>
  	<div>
  	<select autocomplete="off" id="px-feeds" name="px-feeds[]" multiple="multiple" class="zone-txtarea inventory-select">
	</select>
  	</div>
  	<div class="stats-date">
  	<small>Statistics Date: LATEST</small>
  	</div>
  </div>
  
  <div class="inventory-container top-pad">
  	<h4 class="no-pad">Platform Connection Inventory Feeds
  	<br /><small>[ Default Value for new Line Items ]</small></h4>
  	<div>
  	<input type="button" class="btn btn-primary btn-margin" name="AddPcFeed" value="Add" onclick="showChooserPc();" />
  	<input type="button" class="btn btn-primary btn-margin next" name="RemovePcFeed" value="Remove" onclick="removeSelectedPcItems();" />
  	</div>
  	<div>
  	<select autocomplete="off" id="pc-feeds" name="pc-feeds[]" multiple="multiple" class="zone-txtarea inventory-select">
	</select>
  	</div>
  	<div class="stats-date">
  		<small>Statistics Date: </small>
  		<div class="input-append date">
			<input name="stats-date-pc" id="stats-date-pc" class="span2" size="16" type="text" value="<?php echo $yesterday;?>" readonly="readonly" />
			<span class="add-on" id="stats-date-pc-icon"><i class="icon-calendar"></i></span>
		</div>
  	</div>
  </div>
  
  <div class="inventory-container top-pad">
  	<h4 class="no-pad">SSP RTB Publisher Inventory Feeds
  	<br /><small>[ Default Value for new Line Items ]</small></h4>
  	<div>
  	<input type="button" class="btn btn-primary btn-margin" name="AddSspFeed" value="Add" onclick="showChooserSsp();" />
  	<input type="button" class="btn btn-primary btn-margin next" name="RemoveSspFeed" value="Remove" onclick="removeSelectedSspItems();" />
  	</div>
  	<div>
  	<select autocomplete="off" id="ssp-feeds" name="ssp-feeds[]" multiple="multiple" class="zone-txtarea inventory-select">
	</select>
  	</div>
  	<div class="stats-date">
  		<small>Statistics Date: </small>
  		<div class="input-append date">
			<input name="stats-date-ssp" id="stats-date-ssp" class="span2" size="16" type="text" value="<?php echo $yesterday;?>" readonly="readonly" />
			<span class="add-on" id="stats-date-ssp-icon"><i class="icon-calendar"></i></span>
		</div>
  	</div>
  </div>
  
  </div>
  <div class="span12">
    <div class="control-group">
	   <input type="submit" class="btn btn-primary" name="B1" value="Create New Campaign" />
	</div>
	</div>
</fieldset>
</form>

<!-- Invocation Code Modal -->
<div class="modal fade" id="InvocationCodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Site Chooser</h4>
        <button type="button" id="cls-btn" class="btn" data-dismiss="modal" style="position: absolute; right: 15px; top: 15px">Close</button>
     	<button type="button" onclick="addCheckedBoxes();" class="btn btn-default" style="position: absolute; right: 100px; top: 15px">Add To Insertion Order</button>
      </div>
      <div class="modal-body">
        <div>
			<table id="rtb-feed-chooser" class="display compact" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th> </th>
						<th>Site ID</th>
						<th>Domain</th>
						<th>Name</th>
						<th>IAB Cat</th>
						<th>Daily Imps</th>
						<th>Average CPM</th>
						<th>Floor</th>
						<th>Exchange</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th> </th>
						<th>Site ID</th>
						<th>Domain</th>
						<th>Name</th>
						<th>IAB Cat</th>
						<th>Daily Imps</th>
						<th>Average CPM</th>
						<th>Floor</th>
						<th>Exchange</th>
					</tr>
				</tfoot>
			</table>
	</div>				
      </div>
    </div>
  </div>
</div>
<!-- Invocation Code Modal -->