<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/script.js');

$enddate = date('m/d/Y', time() + (86400 * 30));
$minEndDate = explode("/", $enddate);

$this->headScript()->captureStart();?>
$(function() {
	$( "#startdate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
	    onSelect: function(date){
	        var selectedDate = new Date(date);
	        var msecsInADay = 86400000;
	        var endDate = new Date(selectedDate.getTime() + msecsInADay);
	        $("#enddate").datepicker( "option", "minDate", endDate );
	    }
	});
	
	$( '#startdateicon' ).click(function() {
          $('#startdate').datepicker('show');
    });
    
    $( "#enddate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
        minDate:new Date(<?php echo $minEndDate[2];?>,<?php echo $minEndDate[0];?>,<?php echo $minEndDate[1];?>)
	});
	
	$( '#enddateicon' ).click(function() {
          $('#enddate').datepicker('show');
    });
});
<?php $this->headScript()->captureEnd();?>
<style type="text/css">
	/*form label.error, form input.submit {
margin-left: 253px;
} */
</style>
    <ul class="breadcrumb">
    <li><a href="/demand/">Ad Campaigns</a><span class="divider">/</span></li>
    <li>Create Ad Campaign</li>
    </ul>
<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display: none;"></div>
<form id="campaignform" class="form-horizontal form-top-magin" name="campaignform" method="POST" action="/demand/newcampaign">
<fieldset>
	    <div class="control-group">
		<label for="campaignname">Campaign Name</label>
		<input type="text" class="input-medium" name="campaignname">
	</div>
  <div class="control-group">
	    <label for="startdate">Start Date</label>
	   <div class="input-append date">
		  <input name="startdate" id="startdate" class="span2" size="16" type="text" value="<?php echo date('m/d/Y');?>" readonly="readonly" />
		  <span class="add-on" id="startdateicon"><i class="icon-calendar"></i></span>
	   </div>
	</div>
  <div class="control-group">
	    <label for="enddate">End Date</label>
	   <div class="input-append date">
		  <input name="enddate" id="enddate" class="span2" size="16" type="text" value="<?php echo $enddate;?>" readonly="readonly" />
		  <span class="add-on" id="enddateicon"><i class="icon-calendar"></i></span>
	   </div>
	</div>
  <div class="control-group">
		<label for="customername">Customer Name <nobr><span class="hlp"><small><i>(Use this field for your own customer reference if any)</i></small></span></nobr></label>
		<input type="text" class="input-medium" name="customername">
	</div>
	  <div class="control-group">
		<label for="customerid">Customer ID <nobr><span class="hlp"><small><i>(Use this field for your own customer reference if any)</i></small></span></nobr></label>
		<input type="text" name="customerid" class="input-small">
	</div>
  <div class="control-group">
		<label for="maximpressions">Maximum Impressions: <nobr><span class="hlp"><small><i>(Maximum campaign impressions before the bids stop)</i></small></span></nobr></label>
		<input type="text" name="maximpressions" value="1000000"  class="input-small">
	</div>
  <div class="control-group">
		<label for="maxspend">Maximum Spend: <nobr><span class="hlp"><small><i>(Maximum campaign $$$ spent before the bids stop)</i></small></span></nobr></label>
	    <div class="input-prepend">
		<span class="add-on">$</span>
	    <input type="text" value="100.00" class="input-mini" maxlength="20" id="maxspend" name="maxspend">    </div>
	    </div>
	</div>
	  <div class="control-group">
	   <input type="submit" class="btn btn-primary" name="B1" value="Create New Campaign" />
	</div>
</fieldset>
</form>