<?php

$this->headScript()->appendFile($this->basePath() . '/js/filter.js');

$preview_query = $ispreview == true ? "?ispreview=true" : "";
if ($ispreview == true):
	$rtb_banner_id = $bannerpreviewid;
	$ad_campaign_id = $campaignpreviewid;
else:
	$rtb_banner_id = $bannerid;
	$ad_campaign_id = $campaignid;
endif;

$this->headScript()->captureStart(); ?>
var currentStates = "<?php echo $current_states; ?>";
<?php $this->headScript()->captureEnd();  ?>

  <ul class="breadcrumb">
    <li><a href="/demand/<?php echo $preview_query; ?>">Ad Campaigns</a><span class="divider">/</span></li>
    <li><?php echo $bread_crumb_info["BCAdCampaign"]; ?><span class="divider">/</span></li>
    <li><a href="/demand/viewbanner/<?php echo $ad_campaign_id; ?><?php echo $preview_query; ?>">Banners</a><span class="divider">/</span></li>
    <li><?php echo $bread_crumb_info["BCBanner"]; ?><span class="divider">/</span></li>
    <li>Edit Delivery Filter</li>
    </ul>
<div class="formbox">
<form method="POST" action="/demand/editdeliveryfilter">
<fieldset>
<div class="span7">
    <input type="hidden" name="bannerid" value="<?php echo $bannerid; ?>">
	<input type="hidden" name="bannerpreviewid" value="<?php echo $bannerpreviewid; ?>">
	<input type="hidden" name="ispreview" value="<?php echo (string)$ispreview; ?>">
   <div class="control-group">
		<label for="vertical">Vertical : <span class="hlp"><small><i>(ctrl+shift to select mutliple verticals)</i></small></span></label>
<select id="vertical" name="vertical[]" multiple class="zone-txtarea" style="min-height: 200px">
    <?php foreach ($vertical_options as $code => $name): ?>
        <?php if (in_array((string)$code, $current_verticals)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>

<div class="control-group">
		<label for="geocountry">Geo Country : <span class="hlp"><small><i>(ctrl+shift to select mutliple countries)</i></small></span></label>
<select id="geocountry" name="geocountry[]" class="zone-txtarea" multiple style="min-height: 200px" onchange="populateStates();">
    <option value="">[ SELECT A COUNTRY ]</option>
    <?php foreach ($countrylist as $shortcode => $name): ?>
        <?php if (in_array((string)$shortcode, $current_countries)): ?>
            <option value="<?php echo $shortcode?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $shortcode?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
<div class="control-group">
		<label for="geostate">Geo State : <span class="hlp"><small><i>(ctrl+shift to select mutliple states)</i></small></span></label>
		<div id="state-select" style="margin-bottom: 30px;">

  </div>
	</div>
	<div class="control-group">
		<label for="geocity">Geo City : <span class="hlp"><small><i>(comma separate multiple cities)</i></small></span></label>
		<input type="text" id="geocity" name="geocity" value="<?php echo $geocity_option;?>" class="zone-txtbox">
	</div>
<div class="control-group">
		<label for="adtagtype">Ad Tag Type</label>
<select id="adtagtype" name="adtagtype" class="zone-txtarea">
    <?php foreach ($adtagtype_options as $code => $name): ?>
        <?php if ((string)$code === $current_adtagtype): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	<div class="control-group">
		<label for="adpositionminleft">Ad Position Min Left : <span class="hlp"><small><i>(eg. 100 [in px])</i></small></span></label>
		<input type="text" name="adpositionminleft" value="<?php echo $adpositionminleft_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="adpositionmaxleft">Ad Position Max Left : <span class="hlp"><small><i>(eg. 100 [in px])</i></small></span></label>
		<input type="text" name="adpositionmaxleft" value="<?php echo $adpositionmaxleft_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="adpositionmintop">Ad Position Min Top : <span class="hlp"><small><i>(eg. 100 [in px])</i></small></span></label>
		<input type="text" name="adpositionmintop" value="<?php echo $adpositionmintop_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="adpositionmaxtop">Ad Position Max Top : <span class="hlp"><small><i>(eg. 100 [in px])</i></small></span></label>
		<input type="text" name="adpositionmaxtop" value="<?php echo $adpositionmaxtop_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="foldpos">Fold Position</label>
<select id="foldpos" name="foldpos" class="zone-txtarea">
    <?php foreach ($foldpos_options as $code => $name): ?>
        <?php if ((string)$code === $current_foldpos): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
<div class="control-group">
		<label for="frequency">Frequency in last 24 hours</label>
		<input type="text" name="frequency" value="<?php echo $frequency_option;?>" class="input-mini">
	</div>
	</div>
	<div class="span7">
	<div>
		<label for="timezone">Timezone</label>
<select id="timezone" name="timezone[]" class="zone-txtarea" multiple style="min-height: 200px">
    <?php foreach ($timezone_options as $code => $name): ?>
        <?php if (in_array((string)$code, $current_timezones)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	<div class="control-group">
		<label for="iniframe">In An IFrame?</label>
<select id="iniframe" name="iniframe" class="zone-txtarea">
    <?php foreach ($iniframe_options as $code => $name): ?>
        <?php if ((string)$code === $current_iniframe): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
<div class="control-group">
		<label for="inmultiplenestediframes">In Multiple Nested IFrames?</label>
<select id="inmultiplenestediframes" name="inmultiplenestediframes" class="zone-txtarea">
    <?php foreach ($inmultiplenestediframes_options as $code => $name): ?>
        <?php if ((string)$code === $current_inmultiplenestediframes): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
<div class="control-group">
		<label for="minscreenresolutionwidth">Min Screen Resolution Width : <span class="hlp"><small><i>(eg. 500 [in px])</i></small></span></label>
		<input type="text" name="minscreenresolutionwidth" value="<?php echo $minscreenresolutionwidth_option;?>" class="input-mini">
	</div>
<div class="control-group">
		<label for="maxscreenresolutionwidth">Max Screen Resolution Width : <span class="hlp"><small><i>(eg. 1400 [in px])</i></small></span></label>
		<input type="text" name="maxscreenresolutionwidth" value="<?php echo $maxscreenresolutionwidth_option;?>" class="input-mini">
	</div>
<div class="control-group">
		<label for="minscreenresolutionheight">Min Screen Resolution Height : <span class="hlp"><small><i>(eg. 300 [in px])</i></small></span></label>
		<input type="text" name="minscreenresolutionheight" value="<?php echo $minscreenresolutionheight_option;?>" class="input-mini">
	</div>
<div class="control-group">
		<label for="maxscreenresolutionheight">Max Screen Resolution Height : <span class="hlp"><small><i>(eg. 1200 [in px])</i></small></span></label>
		<input type="text" name="maxscreenresolutionheight" value="<?php echo $maxscreenresolutionheight_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="httplanguage">Http Language : <span class="hlp"><small><i>( Example: en-us,en;q=0.5 )</i></small></span></label>
		<input type="text" name="httplanguage" value="<?php echo $httplanguage_option;?>" class="input-medium">
	</div>

<div class="control-group">
		<label for="browseruseragentgrep">Browser User Agent Grep : <span class="hlp"><small><i>( Non-Empty matches UserAgent String, Example: Firefox/23 )</i></small></span></label>
		<input type="text" name="browseruseragentgrep" value="<?php echo $browseruseragentgrep_option;?>" class="zone-txtbox">
	</div>

	<div class="control-group">
		<label for="cookiegrep">Cookie Grep : <span class="hlp"><small><i>( Non-Empty matches Cookie String, Example: pcv:1|uid:123 )</i></small></span></label>
		<input type="text" name="cookiegrep" value="<?php echo $cookiegrep_option;?>" class="zone-txtbox">
	</div>

<div class="control-group">
		<label for="pmpenable">Pmp Enable</label>
<select id="pmpenable" name="pmpenable" class="zone-txtarea"> 
    <?php foreach ($pmpenable_options as $code => $name): ?>
        <?php if ((string)$code === $current_pmpenable): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
   <div class="control-group">
		<label for="secure">Secure</label>
<select id="secure" name="secure"  class="zone-txtarea">
    <?php foreach ($secure_options as $code => $name): ?>
        <?php if ((string)$code === $current_secure): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>

    <div class="control-group">
		<label for="optout">Optout</label>
<select id="optout" name="optout" class="zone-txtarea">
    <?php foreach ($optout_options as $code => $name): ?>
        <?php if ((string)$code === $current_optout): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
	</div>
	<div class="span12">
<div class="control-group">
	   <input type="submit" class="btn btn-primary" name="B1" value="Edit Banner Filter Settings" />
	</div>
	</div>
</fieldset>
</form>
</div>