<?php
$this->headScript()->appendFile($this->basePath() . '/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/datatables/sitechooser.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/datatables/jquery.dataTables.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/datatables/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/datatables/sitechooser.js');

$current_time = time();
$yesterday_time = $current_time - 86400;
$yesterday = date('m/d/Y', $yesterday_time);

$preview_query = $ispreview == true ? "?ispreview=true" : "";

$minEndDate = explode("/", $enddate);

$this->headScript()->captureStart() ?>

<?php if (!empty($campaignid) && intval($campaignid) > 0): ?>
var insertion_order_id = <?php echo $campaignid; ?>;
<?php else: ?>
var insertion_order_id = null;
<?php endif; ?>

$(function() {
	$( "#startdate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
	    onSelect: function(date){
	        var selectedDate = new Date(date);
	        var msecsInADay = 86400000;
	        var endDate = new Date(selectedDate.getTime() + msecsInADay);
	        $("#enddate").datepicker( "option", "setDate", endDate );
	    }
	});
    
    $( "#enddate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: true,
        yearRange: "-1:+6",
        <?php if($minEndDate[2]!='0000'):?>
        setDate:new Date(<?php echo $minEndDate[2];?>,<?php echo $minEndDate[0];?>,<?php echo $minEndDate[1];?>)
       <?php endif;?>
	});
	
	$( "#stats-date-ssp" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: true,
        yearRange: "-1:+6",
	});
	
	$( "#stats-date-pc" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: true,
        yearRange: "-1:+6",
	});
	
	$( '#stats-date-ssp-icon' ).click(function() {
          $('#stats-date-ssp').datepicker('show');
    });
	
	$( '#stats-date-pc-icon' ).click(function() {
          $('#stats-date-pc').datepicker('show');
    });
	
	$( '#startdateicon' ).click(function() {
          $('#startdate').datepicker('show');
    });
	
	$( '#enddateicon' ).click(function() {
          $('#enddate').datepicker('show');
    });
});
<?php $this->headScript()->captureEnd();  ?>


    <ul class="breadcrumb">
    <li><a href="/private-exchange/<?php echo $preview_query; ?>">Insertion Orders</a> <span class="divider">/</span></li>
    <li><?php echo $bread_crumb_info["BCInsertionOrder"]; ?> <span class="divider">/</span></li>
    <li class="active">Edit Insertion Order</li>
    </ul>
    
<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display: none;"></div>
<form onsubmit="highlightSelects();" id="campaignform" name="campaignform" class="form-horizontal form-top-magin" method="POST" action="/private-exchange/newinsertionorder">
<input type="hidden" name="campaignid" value="<?php echo $campaignid;?>">
<input type="hidden" name="campaignpreviewid" value="<?php echo $campaignpreviewid;?>">
<input type="hidden" name="ispreview" value="<?php echo $ispreview;?>">

<fieldset>
<div class="span7">
    <div class="control-group">
		<label for="campaignname" >Order Name</label>
   		<input type="text" class="input-medium" name="campaignname" value="<?php echo $campaignname;?>">
    </div>
    
	<div class="control-group">
      <label for="startdate" >Start Date</label>
        <div class="input-append date">
		  <input name="startdate" id="startdate" class="span2" size="16" type="text" value="<?php echo $startdate;?>" readonly="readonly" />
		  <span class="add-on" id="startdateicon"><i class="icon-calendar"></i></span>
      </div>
	</div>
	
 <div class="control-group">
	 <label for="enddate" >End Date</label>
	  <div class="input-append date">
		  <input name="enddate" id="enddate" class="span2" size="16" type="text" value="<?php echo $enddate;?>" readonly="readonly" />
		  <span class="add-on" id="enddateicon"><i class="icon-calendar"></i></span>
	 </div>
	</div>
	
	 <div class="control-group">
	  <label for="enddate" >Customer Name <span class="hlp"><small><i>(Use this field for your own customer reference if any)</i></small></span></label>
	 		<input type="text" class="input-medium" name="customername" value="<?php echo $customername;?>"> 
	 		<span id="<?php echo $cdn_form_error;?>"></span>
</div>	
	
		 <div class="control-group">
	  <label for="enddate" >Customer ID <span class="hlp"><small><i>(Use this field for your own customer reference if any)</i></small></span></label>
		<input type="text" name="customerid" class="input-small" value="<?php echo $customerid;?>"> 
		 </div>

 <div class="control-group">
	  <label for="enddate" >Maximum Impressions: <span class="hlp"><small><i>(Maximum campaign impressions before the bids stop)</i></small></span></label>
		<input type="text" name="maximpressions" class="input-small" value="<?php echo $maximpressions;?>"> 
 </div>
 
  <div class="control-group">
	  <label for="enddate" >Maximum Spend: <span class="hlp"><small><i>(Maximum campaign $$$ spent before the bids stop)</i></small></span></label>
    <div class="input-prepend">
	<span class="add-on">$</span>
    <input type="text" value="<?php echo $maxspend;?>" class="input-mini" maxlength="20" id="maxspend" name="maxspend">    
    </div>
  </div>
  </div>
  <div class="span7">
  <div class="inventory-container">
  	<h4 class="no-pad">Private Exchange Inventory Feeds
  	<br /><small>[ Default Value for new Line Items ]</small></h4>
  	<div>
  	<input type="button" class="btn btn-primary btn-margin" name="AddPcFeed" value="Add" onclick="showChooserPx();" />
  	<input type="button" class="btn btn-primary btn-margin next" name="RemovePxFeed" value="Remove" onclick="removeSelectedPxItems();" />
  	</div>
  	<div>
  	<select autocomplete="off" id="px-feeds" name="px-feeds[]" multiple="multiple" class="zone-txtarea inventory-select">
  	<?php foreach ($pmp_deal_list as $pmp_deal):
			if ($pmp_deal->PublisherWebsiteLocal == 1 && $pmp_deal->Enabled == 1): ?>
				<option value="<?php echo rawurlencode($pmp_deal->PublisherWebsiteID . '::' . $pmp_deal->PublisherWebsiteDescription); ?>"><?php echo $pmp_deal->PublisherWebsiteDescription; ?></option>
	<?php 	endif;	
		endforeach; ?>
	</select>
  	</div>
  	<div class="stats-date">
  	<small>Statistics Date: LATEST</small>
  	</div>
  </div>
  
  <div class="inventory-container top-pad">
  	<h4 class="no-pad">Platform Connection Inventory Feeds
  	<br /><small>[ Default Value for new Line Items ]</small></h4>
  	<div>
  	<input type="button" class="btn btn-primary btn-margin" name="AddPcFeed" value="Add" onclick="showChooserPc();" />
  	<input type="button" class="btn btn-primary btn-margin next" name="RemovePcFeed" value="Remove" onclick="removeSelectedPcItems();" />
  	</div>
  	<div>
  	<select autocomplete="off" id="pc-feeds" name="pc-feeds[]" multiple="multiple" class="zone-txtarea inventory-select">
  	<?php foreach ($pmp_deal_list as $pmp_deal):
			if ($pmp_deal->PublisherWebsiteLocal == 0 && $pmp_deal->Enabled == 1): ?>
				<option value="<?php echo rawurlencode($pmp_deal->PublisherWebsiteID . '::' . $pmp_deal->PublisherWebsiteDescription); ?>"><?php echo $pmp_deal->PublisherWebsiteDescription; ?></option>
	<?php 	endif;	
		endforeach; ?>
	</select>
  	</div>
  	<div class="stats-date">
  		<small>Statistics Date: </small>
  		<div class="input-append date">
			<input name="stats-date-pc" id="stats-date-pc" class="span2" size="16" type="text" value="<?php echo $yesterday;?>" readonly="readonly" />
			<span class="add-on" id="stats-date-pc-icon"><i class="icon-calendar"></i></span>
		</div>
  	</div>
  </div>
  
  <div class="inventory-container top-pad">
  	<h4 class="no-pad">SSP RTB Publisher Inventory Feeds
  	<br /><small>[ Default Value for new Line Items ]</small></h4>
  	<div>
  	<input type="button" class="btn btn-primary btn-margin" name="AddSspFeed" value="Add" onclick="showChooserSsp();" />
  	<input type="button" class="btn btn-primary btn-margin next" name="RemoveSspFeed" value="Remove" onclick="removeSelectedSspItems();" />
  	</div>
  	<div>
  	<select autocomplete="off" id="ssp-feeds" name="ssp-feeds[]" multiple="multiple" class="zone-txtarea inventory-select">
  	<?php foreach ($ssp_channel_list as $ssp_channel):
			if ($ssp_channel->Enabled == 1): ?>
				<option value="<?php echo rawurlencode(str_replace(':', '__COLON__', $ssp_channel->SspPublisherChannelID) . ':' . str_replace(':', '__COLON__', $ssp_channel->SspExchange) . ':' . $ssp_channel->SspPublisherChannelDescription); ?>"><?php echo $ssp_channel->SspPublisherChannelDescription; ?></option>
	<?php 	endif;	
		endforeach; ?>
	</select>
  	</div>
  	<div class="stats-date">
  		<small>Statistics Date: </small>
  		<div class="input-append date">
			<input name="stats-date-ssp" id="stats-date-ssp" class="span2" size="16" type="text" value="<?php echo $yesterday;?>" readonly="readonly" />
			<span class="add-on" id="stats-date-ssp-icon"><i class="icon-calendar"></i></span>
		</div>
  	</div>
  </div>
  
  </div>
  <div class="span12">
    <div class="control-group">
     <input type="submit" class="btn btn-primary btn-margin" name="B1" value="Edit Campaign" />
    </div>
     </div>
</fieldset>
</form>


<!-- Invocation Code Modal -->
<div class="modal fade" id="InvocationCodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Site Chooser</h4>
        <button type="button" id="cls-btn" class="btn" data-dismiss="modal" style="position: absolute; right: 15px; top: 15px">Close</button>
     	<button type="button" onclick="addCheckedBoxes();" class="btn btn-default" style="position: absolute; right: 100px; top: 15px">Add To Insertion Order</button>
      </div>
      <div class="modal-body">
        <div>
			<table id="rtb-feed-chooser" class="display compact" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th> </th>
						<th>Site ID</th>
						<th>Domain</th>
						<th>Name</th>
						<th>IAB Cat</th>
						<th>Daily Imps</th>
						<th>Average CPM</th>
						<th>Floor</th>
						<th>Exchange</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th> </th>
						<th>Site ID</th>
						<th>Domain</th>
						<th>Name</th>
						<th>IAB Cat</th>
						<th>Daily Imps</th>
						<th>Average CPM</th>
						<th>Floor</th>
						<th>Exchange</th>
					</tr>
				</tfoot>
			</table>
	</div>				
      </div>
    </div>
  </div>
</div>
<!-- Invocation Code Modal -->