<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Testimonials</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>	
</div>


<div class="span12">
<h3 class="testimonials">About NGINAD</h3>
<div class="row">
<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 	</p>

<div class="row">
<h3>We provide:</h3>
<ul class="chart_stars">
<li><b>Advertising services:</b> Lorem ipum dolor sit amet.  Lorem ipum dolor sit amet.</li>
<li><b>Audience  Analytics:</b> Lorem ipum dolor sit amet.  Lorem ipum dolor sit amet.</li>
<li><b>Reader Engagement Tools:</b> Lorem ipum dolor sit amet.  Lorem ipum dolor sit amet.</li>	
</ul>
</div></div><!-- end of row -->

<div class="row">	
<div class="span4 cdnpal_stats">
<h4 class="cdnpal_heading">NGINAD Stats</h4>
<div class="well  alert-info">
	20,000 publishers representing more than a million active websites
</div>
<div class="well  alert-info">
	Over 2 billion daily ad requests
</div>
<div class="well  alert-info">
	Over 300 million daily pageviews
</div>
</div>	
<div class="span7">
<img src="../images/Chart.jpg" />		
</div>		
</div><!-- end of inner row -->
<div class="row contact_row">
<div class="span10 alert alert-info contact_box">
<div class="span4">
<address>
<h3>Contact</h3>
<strong>Phone: </strong>(000) 000-0000<br>
<strong>General Info:</strong> <a href="#myModal1"  data-toggle="modal">info@nginad.com</a><br>
<strong>Support: </strong> <a href="#myModal2"  data-toggle="modal">publishersupport@nginad.com</a>
</address>	
</div>

<div class="span3 pull-right">
<div class="content_address_box">
	<h4>NGINAD</h4>	
	<p>1600 Amphitheatre Parkway
 	<br >
	Mountain View, CA 94043</p>
	</div>
</div>
	
</div>
</div>	<!-- end of contact row -->

</div>

<!-- Modal -->
<div class="contact_popup">
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">Contact NGINAD</h3>
</div>
<div class="modal-body">
    <div class="alert alert-error">
    Error:
    </div>
    <form class="form-horizontal">
    <div class="control-group">
    <label class="control-label" for="name">Name</label>
    <div class="controls">
    <input type="text" id="name" placeholder="Name" class="in_shadow">
    </div>
    </div>
    
     <div class="control-group">
    <label class="control-label" for="email">Email<span class="star">*</span></label>
    <div class="controls">
    <input type="text" id="email" placeholder="Email">
    </div>
    </div>
    
     <div class="control-group">
    <label class="control-label" for="subject">Subject</label>
    <div class="controls">
    <input type="text" id="subject" placeholder="Subject">
    </div>
    </div>
    
    
      <div class="control-group">
    <label class="control-label" for="comments">Comments</label>
    <div class="controls">
   <textarea rows="4" name="comments" id="comments"></textarea>
    </div>
    </div>
    
  
      <div class="control-group">
            <label class="control-label" for="subject">&nbsp;</label>
    <div class="controls">
  <input type="submit" name="submit" id="submit" value="send" class="btn btn-primary input_btn_close" /> <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
    </div>
    </form>
</div>

</div><!-- en of modal1 -->
</div><!-- end of contact_popup -->


<!-- Modal -->
<div class="contact_popup">
<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">Contact NGINAD</h3>
</div>
<div class="modal-body">
 <div class="alert alert-error">
    Error:
    </div>
    <form class="form-horizontal">
    <div class="control-group">
    <label class="control-label" for="name">Name</label>
    <div class="controls">
    <input type="text" id="name" placeholder="Name">
    </div>
    </div>
    
     <div class="control-group">
    <label class="control-label" for="email">Email<span class="star">*</span></label>
    <div class="controls">
    <input type="text" id="email" placeholder="Email">
    </div>
    </div>
    
     <div class="control-group">
    <label class="control-label" for="subject">Subject</label>
    <div class="controls">
    <input type="text" id="subject" placeholder="Subject">
    </div>
    </div>
    
    
      <div class="control-group">
    <label class="control-label" for="comments">Comments</label>
    <div class="controls">
   <textarea rows="4" name="comments" id="comments"></textarea>
    </div>
    </div>
    
  
      <div class="control-group">
            <label class="control-label" for="subject">&nbsp;</label>
    <div class="controls">
  <input type="submit" name="submit" id="submit" value="send" class="btn btn-primary input_btn_close" /> <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
    </div>
    </form>
</div>

</div><!-- en of modal1 -->
</div><!-- end of contact_popup -->

</div>
		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>