<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Job Openings</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>
</div>

<div class="span12 jobs_inner">
<div class="job_row_height">
<ul class="breadcrumb">
  <li><a href="<?php echo $this->serverUrl('/company/jobs');?>">Current Openings</a> <span class="divider">/</span></li>
  <li class="active">Production Support Engineer </li>
</ul>

<div class="row">
<div class="span6">
<h3>Production Support Engineer</h3>
<h5 class="text-warning">NGINAD | Mountain View, CA</h5>
<a href="<?php echo $this->serverUrl('/company/jobs/post/apply/678');?>" class="btn btn-primary">Apply Now</a>
</div>

<div class="span5 pull-right">
<p class="backto_openings text-right"><a href="<?php echo $this->serverUrl('/company/jobs');?>"><i class="icon-arrow-left"></i> Back to Openings</a></p>
</div>

</div><!-- end of row-->


<div class="row top_content_row">
<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. </p>	

<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. </p>	

<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. </p>	

<h5 class="job_req_heading">Responsibilities</h5>
<ul class="ul_jobs_req">
<li><span>Support the 24x7 production environment</span></li>
<li><span>Interact with users to clearly document problems and enhancements.</span></li>
<li><span>Act as a point of escalation for troubleshooting, defect and enhancement reporting for the&nbsp;company's products and services.</span></li>
<li><span>Develop, design and implement support solutions to meet technological needs.</span></li>
<li><span>Write clean, well commented, modular code</span></li>
<li><span>Maintain and enhance existing software</span></li>
<li><span>Interact with quality assurance to deliver quality software</span></li>
<li><span>Work within the development team to ensure modifications are incorporated into the existing code base</span></li>
<li><span>Assist the development team with feature development as needs arise</span></li>
<li><span>Assist the quality assurance team with testing new releases and functionality</span></li>
<li><span>Accurately log actions taken and time spent for support related issues</span></li>
<li><span>Develop support documents, FAQs and knowledgebase articles</span></li>
</ul>

<h5 class="job_req_heading">Responsibilities</h5>
<ul class="ul_jobs_req">
<li><span>Knowledge of object-oriented programming with Java and/or php</span></li>
<li><span>Team-oriented skills including SCM, Revision Control, Defect tracking, and collaboration tools</span></li>
<li><span>Linux development experience is preferred</span></li>
<li><span>Comfortable working in a small-team, fast-paced, start-up environment</span></li>
<li><span>Ability to deliver well-tested modules</span></li>
<li><span>Ability to write clean, well commented, modular code</span></li>
<li><span>BS in C.S. or related degree (or equivalent experience)</span></li>
</ul>


<h5 class="job_req_heading">Responsibilities</h5>
<ul class="ul_jobs_req">
<li><span>Jira specific experience</span></li>
<li><span>Apache/PHP</span></li>
<li><span>MySQL experience</span></li>
<li><span>Hadoop experience</span></li>
<li><span>Experience developing distributed applications</span></li>
<li><span>Experience developing multi-threaded applications</span></li>
</ul>

<p>Position Reports to: Director of Software Engineering </p>

</div><!-- end of content row -->

<div class="row">
<p><a href="<?php echo $this->serverUrl('/company/jobs/post/apply/678');?>" class="btn btn-primary">Apply Now</a></p>	
</div><!-- end of row -->

</div>

</div><!-- end of job_row_height-->

<div class="span12 pull-right">
<p class="jobs_footer_heading">For more information on NGINAD job openings, please contact info@nginad.com.</p>	
</div>

		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>