<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Job Openings</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>
</div>

<div class="span12">
<table class="table table-hover jobs_table">
<tr>
	<td class="table_blue_txt"><a href="<?php echo $this->serverUrl('/company/jobs/post/567');?>">Production Support Engineer</a></td><td class="table_black_txt"><span class="pull-right">Mountain View, CA, United States</span></td>
</tr>
<tr>
<td class="table_blue_txt"><a href="#">Production Support Engineer</a></td><td class="table_black_txt"><span class="pull-right">Mountain View, CA, United States</span></td>
</tr>
<tr>
	<td class="table_blue_txt"><a href="#">Production Support Engineer</a></td><td class="table_black_txt"><span class="pull-right">Mountain View, CA, United States</span></td>
</tr>
<tr>
	<td class="table_blue_txt"><a href="#">Production Support Engineer</a></td><td class="table_black_txt"><span class="pull-right">Mountain View, CA, United States</span></td>
</tr>
<tr>
	<td class="table_blue_txt"><a href="#">Production Support Engineer</a></td><td class="table_black_txt"><span class="pull-right">Mountain View, CA, United States</span></td>
</tr>
<tr>
	<td class="table_blue_txt"><a href="#">Production Support Engineer</a></td><td class="table_black_txt"><span class="pull-right">Mountain View, CA, United States</span></td>
</tr>
</table>
</div>
		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>