<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Meet the NGINAD leadership team</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>
</div>

<div class="span12">
<div class="row  person_bottom">
<div class="span3">
	<img src="https://lh5.googleusercontent.com/-C80S1S64FlQ/AAAAAAAAAAI/AAAAAAAAAgk/IE20nIdmXcA/photo.jpg" class="img-circle img-polaroid leadership_img_top">
</div>

<div class="span8 leadership_padding">
	<h2 class="person_heading">Name</h2>	
	<p class="text-warning">Designation</p>	
	<p class="leadership_text">Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. </p>
</div>
	
</div><!-- end of row -->

<div class="row person_bottom">
<div class="span3">
	<img src="https://lh5.googleusercontent.com/-C80S1S64FlQ/AAAAAAAAAAI/AAAAAAAAAgk/IE20nIdmXcA/photo.jpg" class="img-circle img-polaroid leadership_img_top">
</div>

<div class="span8 leadership_padding">
	<h2 class="person_heading">Name</h2>	
	<p class="text-warning">Designation</p>		
	<p class="leadership_text">Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. </p>
</div>
	
</div><!-- end of row -->

<div class="row person_bottom">
<div class="span3">
	<img src="https://lh5.googleusercontent.com/-C80S1S64FlQ/AAAAAAAAAAI/AAAAAAAAAgk/IE20nIdmXcA/photo.jpg" class="img-circle img-polaroid leadership_img_top">
</div>

<div class="span8 leadership_padding">
	<h2 class="person_heading">Name</h2>	
<p class="text-warning">Designation</p>	
<p class="leadership_text">Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. </p>
</div>
	
</div><!-- end of row -->

<div class="row person_bottom">
<div class="span3">
	<img src="https://lh5.googleusercontent.com/-C80S1S64FlQ/AAAAAAAAAAI/AAAAAAAAAgk/IE20nIdmXcA/photo.jpg" class="img-circle img-polaroid leadership_img_top">
</div>

<div class="span8 leadership_padding">
	<h2 class="person_heading">Name</h2>	
<p class="text-warning">Designation</p>		
	<p class="leadership_text">Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. Lorem Ipsum dolor sit amet. </p>
</div>
	
</div><!-- end of row -->

</div>
		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>