<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Press Releases</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>
</div>

<div class="span12">
   <div class="bs-docs-example">
            <ul id="myTab" class="nav nav-tabs press_tab">
              <li class="active"><a href="#2014a" data-toggle="tab">2014</a></li>
              <li><a href="#2013a" data-toggle="tab">2013</a></li>
              <li><a href="#2012a" data-toggle="tab">2012</a></li>
              <li><a href="#2011a" data-toggle="tab">2011</a></li>
              <li><a href="#2010a" data-toggle="tab">2010</a></li>
              <li><a href="#2009a" data-toggle="tab">2009</a></li>
              <li><a href="#2008a" data-toggle="tab">2008</a></li>
              <li><a href="#2007a" data-toggle="tab">2007</a></li>
            </ul>
            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade in active" id="2014a">
             <table class="table table-striped press_table press_table">
             <tr>
             <td class="span2">May 13, 2014</td><td><a href="/company/press/releases/23423">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
             </table>
              </div>
              <div class="tab-pane fade" id="2013a">
                 <table class="table table-striped press_table">
             <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
             </table>
              </div>
                 <div class="tab-pane fade" id="2012a">
               <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
             <td class="span2">May 13, 2014</td><td>Lorem Ipsum dolor sit amet.</td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>	
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td>Lorem Ipsum dolor sit amet.</td>	
             </tr>
             </table>
              </div>
              
                <div class="tab-pane fade" id="2011a">
                <table class="table table-striped press_table">
             <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
             
               <div class="tab-pane fade" id="2010a">
                <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
            
              <div class="tab-pane fade" id="2009a">
             <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
            
              <div class="tab-pane fade" id="2008a">
                <table class="table table-striped press_table">
           <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
              
                <div class="tab-pane fade" id="2007a">
              <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
              
            
            </div>
          </div>





<h3 class="stories">Featured Stories</h3>





   <div class="bs-docs-example">
            <ul id="myTab1" class="nav nav-tabs press_tab">
              <li class="active"><a href="#2014" data-toggle="tab">2014</a></li>
              <li><a href="#2013" data-toggle="tab">2013</a></li>
              <li><a href="#2012" data-toggle="tab">2012</a></li>
              <li><a href="#2011" data-toggle="tab">2011</a></li>
              <li><a href="#2010" data-toggle="tab">2010</a></li>
              <li><a href="#2009" data-toggle="tab">2009</a></li>
              <li><a href="#2008" data-toggle="tab">2008</a></li>
              <li><a href="#2007" data-toggle="tab">2007</a></li>
            </ul>
            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade in active" id="2014">
             <table class="table table-striped press_table">
             <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
              <div class="tab-pane fade" id="2013">
                 <table class="table table-striped press_table">
          <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
                 <div class="tab-pane fade" id="2012">
               <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
              
                <div class="tab-pane fade" id="2011">
                <table class="table table-striped press_table">
           <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
             
               <div class="tab-pane fade" id="2010">
                <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
            
              <div class="tab-pane fade" id="2009">
             <table class="table table-striped press_table">
             <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
            
              <div class="tab-pane fade" id="2008">
                <table class="table table-striped press_table">
            <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
              
                <div class="tab-pane fade" id="2007">
              <table class="table table-striped press_table">
             <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
                <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
              <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
               <tr>
             <td class="span2">May 13, 2014</td><td><a href="#">Lorem Ipsum dolor sit amet.</a></td>
             </tr>
             </table>
              </div>
              
            
            </div>
          </div>



</div>
		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>