<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Press Release - May 13, 2014</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>
</div>

<div class="span12 press_inner">
<h2 class="text-info">Heading</h2>
<p class="text-warning"><b>Sub Heading</b> </p>
<p>Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. </p>

<p>Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. </p>

<p>Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. </p>

<p>Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. </p>

<h4>About NGINAD</h4>
<p>Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. </p>

<p>Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. Lorem Isum dolor sit amet. </p>

<p>
<address>
<strong>Twitter, Inc.</strong><br>
795 Folsom Ave, Suite 600<br>
San Francisco, CA 94107<br>
<abbr title="Phone">P:</abbr> (123) 456-7890
</address>
</p>
</div>
		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>