<?php 
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?><div class="steps-container step1">
<div class="row headtop">
<div class="span6">
    <h4 class="headbreadcrumb">Testimonials</h4>
    </div>

	</div>    
<div id="main-container">
<div style="margin:40px 0 0 10px;" class="pull-left">

<div class="span3">
<?php echo $this->partial('layout/sidebar', array('sidebar_active' => $sidebar_active));?>
</div>


<div class="span12">

<h3 class="testimonials">General Testimonials</h3>
<div class="well">
<div class="row">
<div class="span2">	<img src="/images/testimonial.png" class="img-polaroid" />	</div>
<div class="span9">
		<img src="/images/left_test.png" class="testimonials_images" />Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. <img src="/images/right_test.png" />
		<h5 class="text-right person_name">Person Name</h5>
	<p class="text-right person_address">somewebsite.com</p>
</div>	
</div>
</div><!-- end of well -->

<div class="well">
<div class="row">
<div class="span2">
	<img src="/images/testimonial.png" class="img-polaroid" />	
</div>
<div class="span9">
	<img src="/images/left_test.png" class="testimonials_images" />Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. <img src="/images/right_test.png" />
	<h5 class="text-right person_name">Person Name</h5>
	<p class="text-right person_address">somewebsite.com</p>
</div>	
</div>
</div><!-- end of well -->

</div>
		</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

   
</div>
            </div>  </div>
</div>