<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'GenericSellsidePartner' => __DIR__ . '/GenericSellsidePartner.php',
  'LoopbackPartner'        => __DIR__ . '/LoopbackPartner.php',
);
