<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Maintenance\Module'                     => __DIR__ . '/Module.php',
  'Maintenance\Controller\IndexController' => __DIR__ . '/src/Maintenance/Controller/IndexController.php',
);
