<?php
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?>
<div class="bs-docs-example">
            <ul class="nav nav-tabs" id="myTab">
              <li><a  href="/users/account">Profile</a></li>
              <li class="active"><a data-toggle="tab" href="#change_password">Change Password</a></li>
              <li><a href="/users/websites">Websites</a></li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div id="change_password" class="tab-pane fade active in">
               <?php 
                if(isset($error_msg) && $error_msg != null):
				    echo '<div id="cdn_form_error" class="alert alert-error" style="margin: 5px;">'.$error_msg.'</div>';
			    endif;
			    if(isset($success_msg1) && $success_msg1 != null):
		    	    echo '<div id="cdn_form_success1" class="alert alert-success" style="margin: 5px;">Password updated successfully.</div>';
			    endif;
			   ?>
               <div id="cdn_change_pass" class="alert alert-error" style="margin: 5px; display:none;"></div>
               <form id="changepassform" name="changepassform" method="POST" action="/users/changepassword">
				<fieldset>
				<div class="form-group">
					<label for="password">Old Password: </label>
					<input type="password" class="input-medium" name="old_password" id="old_password" class="input-mini">
				</div>
				<div class="form-group">
					<label for="password">New Password: </label>
					<input type="password" class="input-medium" name="password" id="password">
				</div>
				<div class="form-group">
					<label for="confirm_password">Confirm password:</label>
					<input type="password" name="confirm_password" class="input-medium" id="confirm_password">
				</div>
				 <div class="form-group">
					<input type="submit" class="btn btn-primary" name="update" value="Change Password" />
				</div>
				</fieldset>
				<input type="hidden" name="user_id" value="<?php echo $user_data->user_id;?>">
			</form>
              </div>
            </div>
          </div>