<?php
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?>

   <ul class="breadcrumb">
    <li><a href="/users/customers">Demand Customer List</a><span class="divider">/</span></li>
    <li>Manage Customer Credit</li>
    </ul>

    
<?php if ($email_sent == true): ?>
<div id="cdn_form_msg" class="alert alert-success" style="margin: 5px;">The <a target="_blank" style="color: #000;" href="/forms/credit.application.pdf">Credit Application</a> Email was Sent to: 
<?php echo $user_data->Email; ?> 
</div>
<?php endif; ?>

<div class="steps-container step1">

    <div id="selection-results" class="steps-box">
   <div class="formbox">  
          <table class="table table-striped table-bordered table-margin">
            <tr>
           <th>
				Demand Customer ID
           </th>
           <th>
                Customer Name
           </th>
           <th>
                Customer Username
           </th>
           <th>
            	Email	
           </th>
           <th>
            	Platform Connection Inventory
           </th>
           <th>
            	SSP RTB Inventory
           </th>
           <th>
            	<a target="_blank" style="color: #fff;" href="/forms/credit.application.pdf">Credit App</a> Last Sent On
           </th>
            <th>
            	<a target="_blank" style="color: #fff;" href="/forms/credit.application.pdf">Credit Application</a> Email
           </th>
           </tr>

    	   <?php 
    	   		$userData = $authUsersFactory->get_row(array("DemandCustomerInfoID" => $user_data->DemandCustomerInfoID));
    	   		$approval = false;
    	   		// fixes bad auth_User data from previous signup bug which was fixed in 1.4
    	   		if (!is_object($userData)):
    	   			continue;
    	   		endif;
    	   		if(isset($userData) && $userData->user_enabled == 1 && $userData->user_verified == 1):
    	   			$approval = true;
    	   		endif;
    	   ?>

           <tr>
           <td>
            <?php echo $user_data->DemandCustomerInfoID; ?>
           </td>
           <td>
            <?php echo $user_data->Name; ?>
            </td>
           <td>
            <?php echo $userData->user_login; ?>
           </td>
           <td>
            <?php echo $user_data->Email; ?>
           </td>
           <td>
            <?php if ($user_data->ApprovedForPlatformConnectionInventory == 1): ?>
            	 <span class="label label-success">Approved</span>
            <?php else: ?>
            	 <span class="label label-info">Not Approved</span>
            <?php endif; ?>
            &nbsp;|&nbsp;
            <?php if ($user_data->ApprovedForPlatformConnectionInventory == 1): ?>
            	 <a href="/users/approveplatformconnectioninventory/<?php echo $user_data->DemandCustomerInfoID; ?>?approve=false">Un-Approve</a>
            <?php else: ?>
            	 <a href="/users/approveplatformconnectioninventory/<?php echo $user_data->DemandCustomerInfoID; ?>?approve=true">Approve</a>
            <?php endif; ?>
           </td>
           <td>
            <?php if ($user_data->ApprovedForSspRtbInventory == 1): ?>
            	 <span class="label label-success">Approved</span>
            <?php else: ?>
            	 <span class="label label-info">Not Approved</span>
            <?php endif; ?>
            &nbsp;|&nbsp;
            <?php if ($user_data->ApprovedForSspRtbInventory == 1): ?>
            	 <a href="/users/approvessprtbinventory/<?php echo $user_data->DemandCustomerInfoID; ?>?approve=false">Un-Approve</a>
            <?php else: ?>
            	 <a href="/users/approvessprtbinventory/<?php echo $user_data->DemandCustomerInfoID; ?>?approve=true">Approve</a>
            <?php endif; ?>
           </td>
           <td>
            <?php 
            	$tme = strtotime($user_data->DateCreditApplicationWasSent);
            if ($tme && $user_data->DateCreditApplicationWasSent != '0000-00-00 00:00:00'):
				echo date("m/d/Y", $tme);
            else:
            	echo "Never";
            endif; ?>
           </td>
           <td>
            <a href="/users/sendcreditapplication/<?php echo $user_data->DemandCustomerInfoID; ?>">Email Credit Application</a>
           </td>
           </tr>
    </table>
    </div>
    </div>
</div>
<div style="clear:both"></div>

<input  type="hidden" name="user_type" id="user_type" value="<?php echo $user_type;?>" />
<!-- Publisher Accept Modal -->
<div class="modal fade" id="UserAcceptModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Customer Accept.</h4>
      </div>
      <div class="modal-body">
      <div id="user_accept_alert_msg" class="alert alert-success" style="display: none;">Error</div>
		<div class="control-group">
		    <label for="desc" class="control-label" id="msg"></label>
	    </div>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="user_accept_yes_btn" class="btn btn-primary" onclick="userAcceptConfirm();">Approve</button>
        <button type="button" class="btn btn-default" id="user_accept_no_btn" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Publisher Accept Modal -->


<!-- Publisher Rejection Modal -->
<input type="hidden" name="modal_user_id" id="modal_user_id" value="0" />
<div class="modal fade" id="UserRejectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Customer Rejection</h4>
      </div>
      <div class="modal-body">
      <div id="user_rejection_alert_msg" class="alert alert-success" style="display: none;">Error</div>
		<div class="control-group">
		    <label for="desc" class="control-label" id="msg"></label>
	    </div>
		<div class="control-group">
		    <label for="desc" class="control-label">Reason for Rejection:</label>
		    <div class="controls">
		    <textarea  id="description" name="description" style="width: 500px;height:130px;"></textarea>    </div>
	    </div>
	<!--<h5 style="color: #b94a48;">This action is IMMEDIATE and NOT REVERSABLE!</h5>-->
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="user_rejection_yes_btn" class="btn btn-primary" onclick="userRejectionConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="user_rejection_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Publisher Rejection Modal -->