<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
	$('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="steps-container step1">
     <div class="span3" style="float: right"> 
         <?php if ($is_super_admin === true): ?>
			
			 <form name="loginas" id="loginas" action="/private-exchange-tools/media-library/loginas" class="forms pull-left"  style="margin-top: 10px;">
			  <span style="font-size: 12px; font-weight: bold;">LOG IN AS USER</span>	<select name="userid" onchange="submitForm();">
			 		<option value="0">Admin (<?php echo $true_user_name; ?>)</option>
					<?php foreach ($user_id_list as $user_info_id => $user_info_name): ?>
						<option <?php 
						if ($user_info_id == $effective_id): 
							$effective_user_in_dashboard = true; 
							echo 'selected="selected"'; 
						endif; ?> value="<?php echo $user_info_id;?>"><?php echo $user_info_name;?></option>
					<?php endforeach; ?>
			 	</select>
			 </form>
     </div>  
<div id="main-container">
<div class="pull-left" style="margin: 10px 0 0 10px;">
<?php if ($effective_id != 0 && $effective_user_in_dashboard === true): ?>

					<form name="searchformedia" id="searchformedia" action="/private-exchange-tools/media-library" method="get" class="forms pull-right" >
					<span style="font-size: 12px; font-weight: bold;">Search for Media:</span>	 <input type="text" name="q" class="" value="<?php echo $search_query;?>">
						<div style="display: inline;">
							<input type="submit" name="search-submit" class="btn actv  btn-small" value="GO" style="margin-left: 8px; margin-bottom: 10px;" />
						</div>
					</form>

			<?php endif; ?>
	<?php endif; ?>
	</div>
	   <div class="formbox">  
	<br clear="all">
    <div id="selection-results">

    <table class="table table-striped table-bordered table-margin">
       <tr>
           <th>
            Name
           </th>
           <th>
            Description
           </th>
           <th>
            Media Type
           </th>
           <th>
            View/Edit
           </th>
           <th>
            Date Created
           </th>
           <th>
            Date Updated
           </th>
           </tr>
	
    <?php 
    /*
     * Types will vary between Native Ad, Display and Video
     * but all DAO objects have 5 fields in common which can be accessed
     */
    foreach ($ad_media_list as $ad_media) : 
    ?>
            <tr>
           <td>
            <?php echo $ad_media->getAdName(); ?>
           </td>
           <td>
            <?php echo $ad_media->getDescription(); ?>
           </td>
           <td>
           	<?php echo $ad_media->getMediaType(); ?>
           </td>
           <td>
           	<a href="/private-exchange-tools/media-library/editnativead/<?php echo $ad_media->NativeAdResponseItemID; ?>">Edit</a>
           </td>
           <td>
           	<?php echo $ad_media->getDateCreated(); ?>
           </td>
           <td>
           	<?php echo $ad_media->getDateUpdated(); ?>
           </td>
           </tr>
    <?php endforeach; ?>
    </table>
</div>
        
    </div>  </div>
</div>
<div style="clear:both"></div>
