<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/zone.js');
$this->headScript()->captureStart() ?>

<?php $this->headScript()->captureEnd();  ?>

<ul class="breadcrumb breadcrumb-heading">
    <li><a href="/publisher/">Domains</a> <span class="divider">/</span></li>
    <li><?php echo $domain_obj->WebDomain;?> <span class="divider">/</span></li>
    <li><a href="/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>">Zones</a><span class="divider">/</span></li>
    <li class="active">Create New Ad Zone</li>
    </ul>
<div class="formbox">
<form id="ad" class="form-horizontal" name="ad" method="post" action="/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>/create" novalidate="novalidate">
<?php 
    if($error_message != "" && $error_message !== null && isset($error_message))
    {
    	echo '<div id="cdn_form_success" class="alert alert-error" style="margin: 5px;">'. $error_message .'</div>';
    }
?>

<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
<div class="control-group">
    <label for="adname" class="control-label">Ad Name</label>
    <div class="controls error">
    <input type="text" value="" class="zone-txtbox" maxlength="255" id="AdName" name="AdName"></div>
    </div>
<div class="control-group">
    <label for="Description" class="control-label">Description</label>
    <div class="controls error">
    <textarea class="zone-txtbox" maxlength="255" id="Description" name="Description"></textarea>   </div>
    </div>
<div class="control-group" id="passback-cg">
    <label for="PassbackAdTag" class="control-label">Passback Ad Tag</label>
    <div class="controls error">
 <textarea class="zone-txtbox" maxlength="5000" id="PassbackAdTag" name="PassbackAdTag"></textarea>    </div>
    </div>
    <div class="control-group" id="floor-cg">
    <label for="FloorPrice" class="control-label">Floor Price</label>
    <div class="controls error">
    <div class="input-prepend">
	<span class="add-on">$</span>
    <input type="text" value="" class="input-mini" maxlength="20" id="FloorPrice" name="FloorPrice"></div>
    </div>
    </div>
    <?php if ($is_admin): ?>
	<div class="form-group">
		<label for="PublisherAdZoneTypeID" class="control-label">Zone type?</label>
		<div class="controls">
        <select id="PublisherAdZoneTypeID"  class="selbox-width" name="PublisherAdZoneTypeID" onchange="switchPublisherAdZoneType();">
            <?php foreach ($publisheradzonetype_options as $code => $name): ?>
                <option value="<?php echo $code;?>"><?php echo $name;?></option>
            <?php endforeach; ?>
        </select>
        <div id="banner-picker"></div>
		</div>
	</div>
	<?php endif; ?>
    <div class="control-group">
     <label for="IsMobileFlag" class="control-label">Is Mobile?</label>
    <div class="controls">
    <label><input type="radio" checked="checked" value="0" id="IsMobileFlag" name="IsMobileFlag">No</label><label><input type="radio" value="1" name="IsMobileFlag">Yes</label>    </div>
    </div>
     
     <div class="control-group">
     <label for="Templates" class="control-label">Templates</label>
    <div class="controls">
    <select onchange="getTemplateSizes(this);" class="zone-txtarea" id="AdTemplateID" name="AdTemplateID">
<?php 
     foreach($AdTemplateList as $key=>$value): 
	 	echo '<option value="'. $key .'">'. $value .'</option>';
	 endforeach;
	 ?>
</select> 
   </div>
    </div>
    
    <div class="control-group">
    <label for="Width" class="control-label">Ad Width</label>
    <div class="controls">
    <input type="text" value="" class="input-mini" size="5" maxlength="10" id="Width" name="Width">
    </div> 
    </div>  
    
    <div class="control-group">
    <label for="Height" class="control-label">Ad Height</label>
    <div class="controls">
    <input type="text" value="" class="input-mini" size="5" maxlength="10" id="Height" name="Height">   </div>
    </div> 
               

<div class="control-group">
    <div class="controls">
    <button name="submit" class="btn btn-margin btn-primary" type="submit" id="submitbutton">Create New Ad Zone</button>
    </div>
    </div>
	<input type="hidden" value="<?php echo $AdOwnerID;?>" name="AdOwnerID">
    <input type="hidden" value="<?php echo $domain_obj->PublisherWebsiteID;?>" name="PublisherWebsiteID">					  
</form>
</div>