<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/zone.js');
$this->headScript()->captureStart() ?>
$(function() {
	$("form.form-horizontal").validate({
	   ignore: ".ignore"
	})
});
<?php $this->headScript()->captureEnd();  ?>

<ul class="breadcrumb breadcrumb-heading">
    <li><a href="/publisher/">Domains</a> <span class="divider">/</span></li>
    <li><?php echo $domain_obj->WebDomain;?> <span class="divider">/</span></li>
    <li><a href="/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>">Zones</a><span class="divider">/</span></li>
    <li class="active">Create New Ad Zone</li>
    </ul>
<div class="formbox">
<form id="ad" class="form-horizontal" name="ad" method="post" action="/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>/create" novalidate="novalidate">
<?php 
    if($error_message != "" && $error_message !== null && isset($error_message))
    {
    	echo '<div id="cdn_form_success" class="alert alert-error" style="margin: 5px;">'. $error_message .'</div>';
    }
?>

<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
<div class="control-group">
    <label for="adname" class="control-label">Ad Name</label>
    <div class="controls error">
    <input type="text" value="" class="zone-txtbox" maxlength="255" id="AdName" name="AdName"></div>
    </div>
<div class="control-group">
    <label for="ImpressionType" class="control-label">Ad Delivery Type</label>
    <div class="controls error">
		<select id="ImpressionType" name="ImpressionType" class="zone-txtarea" onchange="switchImpressionType();">
			<option value="banner">Banner Ad</option>
			<option value="video">Video Ad</option>
		</select>
		</div>
    </div>
<div class="control-group">
    <label for="Description" class="control-label">Description</label>
    <div class="controls error">
    <textarea class="zone-txtbox" maxlength="255" id="Description" name="Description"></textarea>   </div>
    </div>
<div class="control-group">
	<div id="auction-type-wrapper" style="margin: 0px; padding: 0px;">
	    <label for="AuctionType" class="control-label">Auction Type</label>
	    <div class="controls error">
			<select id="AuctionType" name="AuctionType" class="zone-txtarea" onchange="switchAuctionType();">
				<option value="rtb">RTB</option>
				<option value="header">Header Bidding</option>
			</select>
			</div>
	    </div>
    </div>

<div class="control-group" id="passback-wrapper" style="margin: 0px; padding: 0px;">    
	<div class="control-group" id="passback-cg">
    <label for="PassbackAdTag" id="passbackTag" class="control-label">Passback Ad Tag</label>
    <div class="controls error">
 	<textarea class="zone-txtbox ignore" maxlength="5000" id="PassbackAdTag" name="PassbackAdTag"></textarea>    </div>
    </div>
    <div class="control-group" id="floor-cg">
    <label for="FloorPrice" class="control-label">Floor Price</label>
    <div class="controls error">
    <div class="input-prepend">
	<span class="add-on">$</span>
    <input type="text" value="0" class="input-mini" maxlength="20" id="FloorPrice" name="FloorPrice"></div>
    </div>
	</div>
</div>
<div class="control-group" id="header-bidding-wrapper" style="margin: 0px; padding: 0px; display: none;">   

	  <div class="control-group ifheaderbid" id='cg-header-page' >
	  <label for="PageHeader" id="PageHeaderLabel" class="control-label">Add Zone to New Page Header</label>
	  	<div class="controls error">
	  		<input type="text" value="" class="zone-txtbox" size="35" maxlength="50" id="new-page-header" name="new-page-header"> 
	  		<input type="button" class="btn btn-margin" id="PageHeader" name="PageHeader" value="Add" onclick="newPageHeader();" />
	  	</div>
	  	<div class="controls error">
	  	<div id="existing-page-header" style="margin-top: 20px;">
	  		<select id="PageHeaderID" name="PageHeaderID" class="zone-txtarea">
	  			<option value="">- Select Existing Page Header -</option>
				<?php foreach ($current_header_bidding_pagename_list as $name => $value): ?>
					<?php if ($value["PageName"] == $current_header_bidding_pagename): ?>
					<option selected="selected" value="<?php echo $value["PageName"];?>"><?php echo $value["PageName"];?></option>
					<?php else: ?>
					<option value="<?php echo $value["PageName"];?>"><?php echo $value["PageName"];?></option>
					<?php endif; ?>
				<?php endforeach; ?>
			</select>
		</div>
		</div>
	  </div>       
	  <div class="control-group ifheaderbid" id='cg-header-ad-network'>
	  <label for="HeaderBiddingType" id="HeaderBiddingTypeLabel" class="control-label">Add Header Bidding Ad Network to Zone</label>
	  <div class="controls error">
	  		<select id="HeaderBiddingType" name="HeaderBiddingType" class="zone-txtarea">
				<?php foreach ($header_bidding_providers as $name => $value): ?>
					<option value="<?php echo $name;?>"><?php echo $value;?></option>
				<?php endforeach; ?>
			</select>
			<input type="button" class="btn btn-margin" id="AddHeaderBiddingType" name="AddHeaderBiddingType" value="Add" onclick="newHeaderBiddingAdNetwork();" />
		</div>
	  </div>  
	  
    <div id="HeaderBiddingItems" class="ifheaderbid">
    	
    </div>

</div>
    <div class="control-group novideo">
     <label for="IsMobileFlag" class="control-label">Is Mobile?</label>
    <div class="controls">
    <label><input type="radio" checked="checked" value="0" id="IsMobileFlag" name="IsMobileFlag">No</label><label><input type="radio" value="1" name="IsMobileFlag">Yes</label>    </div>
    </div>
     
     <div class="control-group novideo">
     <label for="Templates" class="control-label">Templates</label>
    <div class="controls">
    <select onchange="getTemplateSizes(this);" class="zone-txtarea" id="AdTemplateID" name="AdTemplateID">
<?php 
     foreach($AdTemplateList as $key=>$value): 
	 	echo '<option value="'. $key .'">'. $value .'</option>';
	 endforeach;
	 ?>
</select> 
   </div>
    </div>
    
    <div class="control-group">
    <label for="Width" class="control-label">Ad Width</label>
    <div class="controls">
    <input type="text" value="" class="input-mini" size="5" maxlength="100" id="Width" name="Width">
    </div> 
    </div>  
    
    <div class="control-group">
    <label for="Height" class="control-label">Ad Height</label>
    <div class="controls">
    <input type="text" value="" class="input-mini" size="5" maxlength="100" id="Height" name="Height">   </div>
    </div> 
               
    <div class="control-group nobanner" style="display: none;">
    <label for="MinDuration" class="control-label">Minimum Ad Duration : <span class="hlp"><small><i>(required)</i></small></span></label>
    <div class="controls">
    <input type="text" value="0" class="input-mini" size="5" maxlength="100" id="MinDuration" name="MinDuration">
    </div> 
    </div>  
    
    <div class="control-group nobanner" style="display: none;">
    <label for="MaxDuration" class="control-label">Maximum Ad Duration : <span class="hlp"><small><i>(required)</i></small></span></label>
    <div class="controls">
    <input type="text" value="1000" class="input-mini" size="5" maxlength="100" id="MaxDuration" name="MaxDuration">   </div>
    </div>
               
   <div class="control-group nobanner" style="display: none;">
		<label for="Mimes" class="control-label">Mimes : <span class="hlp"><small><i>(required, ctrl+shift to select mutliple)</i></small></span></label>
		<div class="controls">
<select id="Mimes" name="Mimes[]" multiple class="zone-txtarea" style="min-height: 170px">
    <?php foreach ($mimes as $name): ?>
    	<option value="<?php echo $name;?>" selected="selected"><?php echo $name;?></option>
    <?php endforeach; ?>
</select>
	</div>
	</div> 
	
   <div class="control-group nobanner" style="display: none;">
		<label for="Protocols" class="control-label">Protocols : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="controls">
<select id="Protocols" name="Protocols[]" multiple class="zone-txtarea" style="min-height: 50px">
    <?php foreach ($protocols as $code => $name): ?>
        <?php if (in_array((string)$code, $current_protocols)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div> 
	
   <div class="control-group nobanner" style="display: none;">
		<label for="ApisSupported" class="control-label">Apis Supported : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
<div class="controls">
	<select id="ApisSupported" name="ApisSupported[]" multiple class="zone-txtarea" style="min-height: 130px">
    <?php foreach ($apis_supported as $code => $name): ?>
        <?php if (in_array((string)$code, $current_apis_supported)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div>
	
   <div class="control-group nobanner" style="display: none;">
		<label for="Delivery" class="control-label">Video Delivery : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
<div class="controls">
<select id="Delivery" name="Delivery[]" multiple class="zone-txtarea" style="min-height: 50px">
    <?php foreach ($delivery_methods as $code => $name): ?>
        <?php if (in_array((string)$code, $current_delivery_methods)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div>
	
   <div class="control-group nobanner" style="display: none;">
		<label for="Playback" class="control-label">Video Playback : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="controls">
		<select id="Playback" name="Playback[]" multiple class="zone-txtarea" style="min-height: 90px">
    <?php foreach ($playback_methods as $code => $name): ?>
        <?php if (in_array((string)$code, $current_playback_methods)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div>
	
   <div class="control-group nobanner" style="display: none;">
		<label for="StartDelay" class="control-label">Start Delay :</label>
		<div class="controls">
<select id="StartDelay" name="StartDelay">
    <?php foreach ($start_delay as $code => $name): ?>
        <?php if ((string)$code == $current_start_delay): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div>
	
   <div class="control-group nobanner" style="display: none;">
		<label for="Linearity" class="control-label">Linearity :</label>
		<div class="controls">
<select id="Linearity" name="Linearity">
    <?php foreach ($linearity as $code => $name): ?>
        <?php if ((string)$code == $current_start_delay): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div>
	
   <div class="control-group nobanner" style="display: none;">
		<label for="FoldPos" class="control-label">Fold Position :</label>
		<div class="controls">
<select id="FoldPos" name="FoldPos">
    <?php foreach ($fold_pos as $code => $name): ?>
        <?php if ((string)$code == $current_fold_pos): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	</div>
	
<div class="control-group">
    <div class="controls">
    <button name="submit" class="btn btn-margin btn-primary" type="submit" id="submitbutton">Create New Ad Zone</button>
    </div>
    </div>
	<input type="hidden" value="<?php echo $AdOwnerID;?>" name="AdOwnerID">
    <input type="hidden" value="<?php echo $domain_obj->PublisherWebsiteID;?>" name="PublisherWebsiteID">					  
</form>
</div>

<!-- START DYNAMIC HEADER BIDDING DOM ELEMENTS -->

		<div id="header-bidding-type-appnexus" style="display: none;">
			<input type="hidden" name="HBType_N_" value="appnexus" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>AppNexus Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#appnexus">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="PlacementID_N_" class="control-label">placementId
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="234234" class="input-small"
						size="5" maxlength="100" id="PlacementID_N_" name="PlacementID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="RandomKey_N_" class="control-label">randomeKey
					: <span class="hlp"><small><i>(optional)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="Key Value" class="input-small"
						size="5" maxlength="100" id="RandomKey_N_" name="RandomKey_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove AppNexus Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-rubicon" style="display: none;">
			<input type="hidden" name="HBType_N_" value="rubicon" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>Rubicon Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#rubicon">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="RpAccount_N_" class="control-label">rp_account
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="4934" class="input-small"
						size="5" maxlength="100" id="RpAccount_N_" name="RpAccount_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="RpSite_N_" class="control-label">rp_site
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="13945" class="input-mini"
						size="5" maxlength="100" id="RpSite_N_" name="RpSite_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="RpZoneSize_N_" class="control-label">rp_zonesize
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="23948-15" class="input-small"
						size="5" maxlength="100" id="RpZoneSize_N_" name="RpZoneSize_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove Rubicon Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-openx" style="display: none;">
			<input type="hidden" name="HBType_N_" value="openx" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>OpenX Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#openx">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="JsTagUrl_N_" class="control-label">jstag_url
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="ox-d.xyz.servedbyopenx.com/w/1.0/jstag?ef=db&nc=23923-EF" class="input-medium"
						size="5" maxlength="100" id="JsTagUrl_N_" name="JsTagUrl_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="PgId_N_" class="control-label">pgid
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="534205285" class="input-small"
						size="5" maxlength="100" id="PgId_N_" name="PgId_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Unit_N_" class="control-label">unit
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="538562284" class="input-small"
						size="5" maxlength="100" id="Unit_N_" name="Unit_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove OpenX Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-pubmatic" style="display: none;">
			<input type="hidden" name="HBType_N_" value="pubmatic" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>Pubmatic Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#pubmatic">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="PublisherID_N_" class="control-label">publisherId
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="32572" class="input-small"
						size="5" maxlength="100" id="PublisherID_N_" name="PublisherID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="AdSlot_N_" class="control-label">adSlot
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="38519891@300x250" class="input-large"
						size="5" maxlength="100" id="AdSlot_N_" name="AdSlot_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove Pubmatic Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-criteo" style="display: none;">
			<input type="hidden" name="HBType_N_" value="criteo" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>Criteo Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#criteo">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="NID_N_" class="control-label">nid
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="1234" class="input-small"
						size="5" maxlength="100" id="NID_N_" name="NID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="CookieName_N_" class="control-label">cookiename
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="ckn_pub" class="input-small"
						size="5" maxlength="100" id="CookieName_N_" name="CookieName_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="VarName_N_" class="control-label">varname
					: <span class="hlp"><small><i>(optional)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="crtg_content" class="input-small"
						size="5" maxlength="100" id="VarName_N_" name="VarName_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove Criteo Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-yieldbot" style="display: none;">
			<input type="hidden" name="HBType_N_" value="yieldbot" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>Yieldbot Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#yieldbot">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="Psn_N_" class="control-label">psn
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="Psn_N_" name="Psn_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Slot_N_" class="control-label">slot
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="Slot_N_" name="Slot_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove Yieldbot Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-indexexchange" style="display: none;">
			<input type="hidden" name="HBType_N_" value="indexexchange" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>Casale Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#casale-index">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="ID_N_" class="control-label">id
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="ID_N_" name="ID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="SiteID_N_" class="control-label">siteID
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="SiteID_N_" name="SiteID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Tier2SiteID_N_" class="control-label">tier2SiteID
					: <span class="hlp"><small><i>(optional)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="Tier2SiteID_N_" name="Tier2SiteID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Tier3SiteID_N_" class="control-label">tier3SiteID
					: <span class="hlp"><small><i>(optional)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="Tier3SiteID_N_" name="Tier3SiteID_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove Casale Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-sovrn" style="display: none;">
			<input type="hidden" name="HBType_N_" value="sovrn" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>Sovrn Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#sovrn">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="TagID_N_" class="control-label">tag_id
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="315045" class="input-small"
						size="5" maxlength="100" id="TagID_N_" name="TagID_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove Sovrn Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-aol" style="display: none;">
			<input type="hidden" name="HBType_N_" value="aol" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>AOL Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#aol">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="Placement_N_" class="control-label">placement
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="23324932" class="input-small"
						size="5" maxlength="100" id="Placement_N_" name="Placement_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Network_N_" class="control-label">network
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="" class="input-small"
						size="5" maxlength="100" id="Network_N_" name="Network_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="SizeID_N_" class="control-label">sizeId
					: <span class="hlp"><small><i>(optional)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="170" class="input-small"
						size="5" maxlength="100" id="SizeID_N_" name="SizeID_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Alias_N_" class="control-label">alias
					: <span class="hlp"><small><i>(optional)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="desktop_articlepage_something_box_300_250" class="input-xlarge"
						size="5" maxlength="100" id="Alias_N_" name="Alias_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove AOL Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
		<div id="header-bidding-type-pulsepoint" style="display: none;">
			<input type="hidden" name="HBType_N_" value="pulsepoint" />
			<input type="hidden" id="HeaderBiddingAdUnitID_N_" name="HeaderBiddingAdUnitID_N_" value="new" />
			<h3>PulsePoint Header Bidder - <small><i><a target="_blank" href="http://prebid.org/dev-docs/bidders.html#pulsepoint">[ See Options ]</a></i></small></h3>
			<div class="control-group">
				<label for="Cf_N_" class="control-label">cf
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="300X250" class="input-small"
						size="5" maxlength="100" id="Cf_N_" name="Cf_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Cp_N_" class="control-label">cp
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="12345" class="input-small"
						size="5" maxlength="100" id="Cp_N_" name="Cp_N_">
				</div>
			</div>
			<div class="control-group">
				<label for="Ct_N_" class="control-label">ct
					: <span class="hlp"><small><i>(required)</i></small></span>
				</label>
				<div class="controls">
					<input type="text" placeholder="12345" class="input-small"
						size="5" maxlength="100" id="Ct_N_" name="Ct_N_">
				</div>
			</div>
			<div class="control-group">
		    	<label for="NetworkAdTag_N_" class="control-label">Ad Tag</label>
		    	<div class="controls error">
		 			<textarea class="zone-txtbox ignore" maxlength="5000" id="NetworkAdTag_N_" name="NetworkAdTag_N_"></textarea>    
		 		</div>
		    </div>
		    <div class="control-group">
				<div class="n-button-container">
					<input type="button" class="btn btn-margin" name="RemoveHBType_N_" value="Remove PulsePoint Bidder" onclick="removeHeaderBiddingAdNetwork('_N_');" />
				</div>
			</div>
		</div>
		
<!-- END DYNAMIC HEADER BIDDING DOM ELEMENTS -->

		