<?php

$this->headScript()->appendFile($this->basePath() . '/js/script.js');

$this->headScript()->captureStart() ?>
function submitForm() {
	$('#loginas').submit();
}
<?php $this->headScript()->captureEnd();  ?>
<div class="steps-container step1">
   
   <ul class="breadcrumb breadcrumb-heading">
    <li><a href="/publisher/">Domains</a><span class="divider">/</span></li>
    <li><?php echo $domain_obj->WebDomain;?> <span class="divider">/</span></li>
    <li class="active">Zones</li>
    </ul>
    
 <?php        
  if($error_message != "" && $error_message !== null && isset($error_message)):

                  echo "<div style=\"font-weight:bold;color:#FF0000;font-size:110%;\">";
                  echo $error_message;
                  echo "</div>";
  endif;
?>                      
 <div class="formbox">  
    <div id="selection-results" class="steps-box">
        <table class="table table-striped table-bordered table-margin">
            <tr>
            <?php 
            foreach($zone_list['header'] as $order => $title):
            	if ($title == "AutoApprove"):
            		continue;
            	endif;
                echo "\n<th style=\"text-align:center;\">" . $title . "</th>\n"; 
            endforeach;
            ?>
            </tr>
            <?php
            if(count($zone_list["data"]) > 0):
                foreach ($zone_list["data"] AS $row_number => $row_data):
                	$is_rejected = false;
            ?>
                <tr>
                    <td><?php echo $row_number+1; ?></td>
                    <?php foreach ($row_data AS $column_key => $data):

                    	if ($zone_list["meta"][$column_key] == 'AutoApprove'):
                    		continue;
                    	endif;
	                    $auto_approved = $zone_list_raw[$row_number]["AutoApprove"];
	                    $domain_id = $zone_list_raw[$row_number]["PublisherWebsiteID"];
	                    $ad_id = $zone_list_raw[$row_number]["PublisherAdZoneID"];
	                    
	                    $impression_type = $zone_list_raw[$row_number]["ImpressionType"];
                        
                                // Change display format according to column specified.
                                switch($zone_list["meta"][$column_key]):
                                    case "AdName":
                                        echo '<td>' . $data . " (" . $ad_id .")" . '</td>';
                                        break; 
                                	case "AdStatus":
                                		$approve_verb = 'Approve';
                                		$reject_verb = 'Reject';
                                		$approved_verb = 'Approved';
                                		$pending_verb = 'Pending';
                                		$rejected_verb = 'Rejected';

                                		if ($auto_approved == 1):
                                			$approved_verb = 'Auto-Approved';
                                		endif;
                                	    $admin_approval = array(
                                	           0 => "<strong>" . $pending_verb . "</strong><br /><a href=\"/publisher/zone/" . $domain_id . "/approve/" . $ad_id . "\">" . $approve_verb . "</a>"
												. "<br /><a href=\"/publisher/zone/" . $domain_id . "/reject/" . $ad_id . "\">" . $reject_verb . "</a>",
                                               1 => "<a href=\"/publisher/zone/" . $domain_id . "/reject/" . $ad_id . "\">" . $approved_verb . "</a>",
											   2 => "<a href=\"/publisher/zone/" . $domain_id . "/approve/" . $ad_id . "\">" . $rejected_verb . "</a>"
    			 	                           );
                                	    $approval = array(0=>$pending_verb,1=>$approved_verb,2=>$rejected_verb);
                                	    
                                	    if (intval($data) == 2):
                                	    	$is_rejected = true;
                                	    endif;
                                	    
                                	    if($is_admin)
                                	        echo '<td>' . $admin_approval[intval($data)] . '</td>';
                                	    else
                                	        echo '<td>' . $approval[intval($data)] . '</td>';
                                        break;
                                	case "AdTemplateID":
                                		
                                		if ($impression_type == 'video'):
                                			echo '<td>' . "VAST Video" . '</td>';
                                	    elseif($data == 0):
                                	        echo '<td>' . "Custom:<br />" . 
                                	           $zone_list_raw[$row_number]["Width"] . " x " .
                                	           $zone_list_raw[$row_number]["Height"] . '</td>';
                                	    else:
                                	        echo '<td>' . $zone_list_raw[$row_number]["TemplateName"] . ":<br />" .
                                    	        $zone_list_raw[$row_number]["TemplateX"] . " x " .
                                    	        $zone_list_raw[$row_number]["TemplateY"] . '</td>';
                                	    endif;
                                	    break;
                                	case "TotalRequests":
                                	case "TotalImpressionsFilled":
                                	    echo '<td style="text-align: right">' . number_format($data) . '</td>';
                                	    break;
                                	case "TotalAmount":
                                	case "FloorPrice":
                                	    echo '<td style="text-align: right">' . '$' . sprintf("%1.2f", $data) . '</td>';
                                	    break;
                                    default:
                                        echo '<td>' . $data . '</td>';
                                        break;
                                endswitch;
                            endforeach; ?>
                    <td>
                    <?php if ($is_admin === true || $is_rejected !== true): ?>
                    	<a href="/publisher/zone/<?php echo $domain_id;?>/edit/<?php echo $ad_id;?>">Edit 

Zone</a>&nbsp;&nbsp;&nbsp;
<?php if ($impression_type == 'video'): ?>
                    	<a href="javascript:void(0);" onclick="VastInvocationShow(<?php echo 
$domain_id;?>, <?php echo $zone_list_raw[$row_number]["PublisherAdZoneID"];?>)">Get VAST URL</a>
<?php else: ?>
                    	<a href="javascript:void(0);" onclick="InvocationShow(<?php echo 
$domain_id;?>, <?php echo $zone_list_raw[$row_number]["PublisherAdZoneID"];?>)">Invocation Code</a>
<?php endif; ?>
                        <hr width="100%" />
                        <!--<a href="/publisher/zone/<?php echo $domain_id; ?>/delete/<?php echo $ad_id; ?>">Delete Zone</a>-->
                        <a href="javascript:void(0);" onclick="deleteZoneModal(<?php echo $domain_id;?>,<?php echo $ad_id;?>,'<?php echo $zone_list_raw[$row_number]["AdName"];?>');">Delete Zone</a>
                    <?php else: ?>
                        &nbsp;
                    <?php endif; ?>
                    </td>
                </tr>
            <?php 
                endforeach;
            else: ?>
                <tr>
                    <td colspan="<?php echo count($zone_list['header']); ?>" style="text-align:center;">There are no results</td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
</div>

<!-- Invocation Code Modal -->
<div class="modal fade" id="InvocationCodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Copy/Paste Ad Tag</h4>
      </div>
      <div class="modal-body">
        <div>
		<p>For most websites just copy & paste the code below into the HTML source of the page where you want to the ad to display.</p>
		<label for="adtag">&nbsp;</label>
		<div id="adtag_progress_bar" class="progress progress-striped active">
             <div class="bar" style="width: 100%;"></div>
         </div>
		<textarea rows="6" name="adtag" id="adtag" style="min-width: 516px;display: none;"></textarea>
		
	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Invocation Code Modal -->

<!-- Invocation Code Modal VAST -->
<div class="modal fade" id="InvocationCodeModalVast" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabelVast">Embed VAST Video URL in Flash Movie Player</h4>
      </div>
      <div class="modal-body">
        <div>
		<p>Use this VAST URL where you would normally copy paste a <a target="_blank" href="http://ad3.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2">LiveRail URL</a></p>
		<label for="adtag">&nbsp;</label>
		<div id="adtag_progress_bar_vast" class="progress progress-striped active">
             <div class="bar" style="width: 100%;"></div>
         </div>
		<textarea rows="1" name="adtagvast" id="adtagvast" style="min-width: 516px;display: none;"></textarea>
		<br />
		<img src="/images/vast.tag.jpg" />
	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Invocation Code Modal VAST -->

<!-- Zone Delete Modal -->
<input  type="hidden" name="modal_domain_id" id="modal_domain_id" value="0" />
<input  type="hidden" name="modal_zone_id" id="modal_zone_id" value="0" />
<div class="modal fade" id="DeleteZoneModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Zone</h4>
      </div>
      <div class="modal-body">
      <div id="zone_alert_msg" class="alert alert-error" style="display: none;">Error</div>
		<p id="msg"></p>
<h5 style="color: #b94a48;">This action is IMMEDIATE and NOT REVERSABLE!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="zone_yes_btn" class="btn btn-primary" onclick="deleteZoneConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="zone_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Zone Delete Modal -->
